/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIGenerateUnitedOrdersRequest.h
 *
 * Данные, необходимые для генерации отчета. 
 */

#ifndef OAIGenerateUnitedOrdersRequest_H
#define OAIGenerateUnitedOrdersRequest_H

#include <QJsonObject>

#include <QDate>
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIGenerateUnitedOrdersRequest : public OAIObject {
public:
    OAIGenerateUnitedOrdersRequest();
    OAIGenerateUnitedOrdersRequest(QString json);
    ~OAIGenerateUnitedOrdersRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getBusinessId() const;
    void setBusinessId(const qint64 &business_id);
    bool is_business_id_Set() const;
    bool is_business_id_Valid() const;

    QDate getDateFrom() const;
    void setDateFrom(const QDate &date_from);
    bool is_date_from_Set() const;
    bool is_date_from_Valid() const;

    QDate getDateTo() const;
    void setDateTo(const QDate &date_to);
    bool is_date_to_Set() const;
    bool is_date_to_Valid() const;

    QList<qint64> getCampaignIds() const;
    void setCampaignIds(const QList<qint64> &campaign_ids);
    bool is_campaign_ids_Set() const;
    bool is_campaign_ids_Valid() const;

    QString getPromoId() const;
    void setPromoId(const QString &promo_id);
    bool is_promo_id_Set() const;
    bool is_promo_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 m_business_id;
    bool m_business_id_isSet;
    bool m_business_id_isValid;

    QDate m_date_from;
    bool m_date_from_isSet;
    bool m_date_from_isValid;

    QDate m_date_to;
    bool m_date_to_isSet;
    bool m_date_to_isValid;

    QList<qint64> m_campaign_ids;
    bool m_campaign_ids_isSet;
    bool m_campaign_ids_isValid;

    QString m_promo_id;
    bool m_promo_id_isSet;
    bool m_promo_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIGenerateUnitedOrdersRequest)

#endif // OAIGenerateUnitedOrdersRequest_H
