/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIOfferPriceByOfferIdsListResponseDTO.h
 *
 * Список цен.
 */

#ifndef OAIOfferPriceByOfferIdsListResponseDTO_H
#define OAIOfferPriceByOfferIdsListResponseDTO_H

#include <QJsonObject>

#include "OAIOfferPriceByOfferIdsResponseDTO.h"
#include "OAIScrollingPagerDTO.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIOfferPriceByOfferIdsResponseDTO;
class OAIScrollingPagerDTO;

class OAIOfferPriceByOfferIdsListResponseDTO : public OAIObject {
public:
    OAIOfferPriceByOfferIdsListResponseDTO();
    OAIOfferPriceByOfferIdsListResponseDTO(QString json);
    ~OAIOfferPriceByOfferIdsListResponseDTO() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIOfferPriceByOfferIdsResponseDTO> getOffers() const;
    void setOffers(const QList<OAIOfferPriceByOfferIdsResponseDTO> &offers);
    bool is_offers_Set() const;
    bool is_offers_Valid() const;

    OAIScrollingPagerDTO getPaging() const;
    void setPaging(const OAIScrollingPagerDTO &paging);
    bool is_paging_Set() const;
    bool is_paging_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIOfferPriceByOfferIdsResponseDTO> m_offers;
    bool m_offers_isSet;
    bool m_offers_isValid;

    OAIScrollingPagerDTO m_paging;
    bool m_paging_isSet;
    bool m_paging_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIOfferPriceByOfferIdsListResponseDTO)

#endif // OAIOfferPriceByOfferIdsListResponseDTO_H
