=begin
#Партнерский API Маркета

#API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

The version of the OpenAPI document: LATEST

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module OpenapiClient
  class TurnoverType
    LOW = "LOW".freeze
    ALMOST_LOW = "ALMOST_LOW".freeze
    HIGH = "HIGH".freeze
    VERY_HIGH = "VERY_HIGH".freeze
    NO_SALES = "NO_SALES".freeze
    FREE_STORE = "FREE_STORE".freeze

    def self.all_vars
      @all_vars ||= [LOW, ALMOST_LOW, HIGH, VERY_HIGH, NO_SALES, FREE_STORE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TurnoverType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TurnoverType"
    end
  end
end
