/*
 * business_settings_dto.h
 *
 * Настройки кабинета.
 */

#ifndef _business_settings_dto_H_
#define _business_settings_dto_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct business_settings_dto_t business_settings_dto_t;

#include "currency_type.h"

// Enum  for business_settings_dto

typedef enum  { _api__business_settings_dto__NULL = 0, _api__business_settings_dto__RUR, _api__business_settings_dto__USD, _api__business_settings_dto__EUR, _api__business_settings_dto__UAH, _api__business_settings_dto__AUD, _api__business_settings_dto__GBP, _api__business_settings_dto__BYR, _api__business_settings_dto__BYN, _api__business_settings_dto__DKK, _api__business_settings_dto__ISK, _api__business_settings_dto__KZT, _api__business_settings_dto__CAD, _api__business_settings_dto__CNY, _api__business_settings_dto__NOK, _api__business_settings_dto__XDR, _api__business_settings_dto__SGD, _api__business_settings_dto___TRY, _api__business_settings_dto__SEK, _api__business_settings_dto__CHF, _api__business_settings_dto__JPY, _api__business_settings_dto__AZN, _api__business_settings_dto__ALL, _api__business_settings_dto__DZD, _api__business_settings_dto__AOA, _api__business_settings_dto__ARS, _api__business_settings_dto__AMD, _api__business_settings_dto__AFN, _api__business_settings_dto__BHD, _api__business_settings_dto__BGN, _api__business_settings_dto__BOB, _api__business_settings_dto__BWP, _api__business_settings_dto__BND, _api__business_settings_dto__BRL, _api__business_settings_dto__BIF, _api__business_settings_dto__HUF, _api__business_settings_dto__VEF, _api__business_settings_dto__KPW, _api__business_settings_dto__VND, _api__business_settings_dto__GMD, _api__business_settings_dto__GHS, _api__business_settings_dto__GNF, _api__business_settings_dto__HKD, _api__business_settings_dto__GEL, _api__business_settings_dto__AED, _api__business_settings_dto__EGP, _api__business_settings_dto__ZMK, _api__business_settings_dto__ILS, _api__business_settings_dto__INR, _api__business_settings_dto__IDR, _api__business_settings_dto__JOD, _api__business_settings_dto__IQD, _api__business_settings_dto__IRR, _api__business_settings_dto__YER, _api__business_settings_dto__QAR, _api__business_settings_dto__KES, _api__business_settings_dto__KGS, _api__business_settings_dto__COP, _api__business_settings_dto__CDF, _api__business_settings_dto__CRC, _api__business_settings_dto__KWD, _api__business_settings_dto__CUP, _api__business_settings_dto__LAK, _api__business_settings_dto__LVL, _api__business_settings_dto__SLL, _api__business_settings_dto__LBP, _api__business_settings_dto__LYD, _api__business_settings_dto__SZL, _api__business_settings_dto__LTL, _api__business_settings_dto__MUR, _api__business_settings_dto__MRO, _api__business_settings_dto__MKD, _api__business_settings_dto__MWK, _api__business_settings_dto__MGA, _api__business_settings_dto__MYR, _api__business_settings_dto__MAD, _api__business_settings_dto__MXN, _api__business_settings_dto__MZN, _api__business_settings_dto__MDL, _api__business_settings_dto__MNT, _api__business_settings_dto__NPR, _api__business_settings_dto__NGN, _api__business_settings_dto__NIO, _api__business_settings_dto__NZD, _api__business_settings_dto__OMR, _api__business_settings_dto__PKR, _api__business_settings_dto__PYG, _api__business_settings_dto__PEN, _api__business_settings_dto__PLN, _api__business_settings_dto__KHR, _api__business_settings_dto__SAR, _api__business_settings_dto__RON, _api__business_settings_dto__SCR, _api__business_settings_dto__SYP, _api__business_settings_dto__SKK, _api__business_settings_dto__SOS, _api__business_settings_dto__SDG, _api__business_settings_dto__SRD, _api__business_settings_dto__TJS, _api__business_settings_dto__THB, _api__business_settings_dto__TWD, _api__business_settings_dto__BDT, _api__business_settings_dto__TZS, _api__business_settings_dto__TND, _api__business_settings_dto__TMM, _api__business_settings_dto__UGX, _api__business_settings_dto__UZS, _api__business_settings_dto__UYU, _api__business_settings_dto__PHP, _api__business_settings_dto__DJF, _api__business_settings_dto__XAF, _api__business_settings_dto__XOF, _api__business_settings_dto__HRK, _api__business_settings_dto__CZK, _api__business_settings_dto__CLP, _api__business_settings_dto__LKR, _api__business_settings_dto__EEK, _api__business_settings_dto__ETB, _api__business_settings_dto__RSD, _api__business_settings_dto__ZAR, _api__business_settings_dto__KRW, _api__business_settings_dto__NAD, _api__business_settings_dto__TL, _api__business_settings_dto__UE } _api__business_settings_dto__e;

char* business_settings_dto_currency_ToString(_api__business_settings_dto__e currency);

_api__business_settings_dto__e business_settings_dto_currency_FromString(char* currency);



typedef struct business_settings_dto_t {
    int only_default_price; //boolean
    currency_type_t *currency; // custom

} business_settings_dto_t;

business_settings_dto_t *business_settings_dto_create(
    int only_default_price,
    currency_type_t *currency
);

void business_settings_dto_free(business_settings_dto_t *business_settings_dto);

business_settings_dto_t *business_settings_dto_parseFromJSON(cJSON *business_settings_dtoJSON);

cJSON *business_settings_dto_convertToJSON(business_settings_dto_t *business_settings_dto);

#endif /* _business_settings_dto_H_ */

