/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetBusinessSettingsResponse.h
 *
 * Ответ на запрос настроек кабинета.
 */

#ifndef GetBusinessSettingsResponse_H_
#define GetBusinessSettingsResponse_H_



#include "ApiResponseStatusType.h"
#include "GetBusinessSettingsInfoDTO.h"
#include <memory>
#include <vector>
#include <array>
#include <boost/property_tree/ptree.hpp>
#include "ApiResponse.h"
#include "helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Ответ на запрос настроек кабинета.
/// </summary>
class  GetBusinessSettingsResponse : public ApiResponse
{
public:
    GetBusinessSettingsResponse() = default;
    explicit GetBusinessSettingsResponse(boost::property_tree::ptree const& pt);
    virtual ~GetBusinessSettingsResponse() = default;

    GetBusinessSettingsResponse(const GetBusinessSettingsResponse& other) = default; // copy constructor
    GetBusinessSettingsResponse(GetBusinessSettingsResponse&& other) noexcept = default; // move constructor

    GetBusinessSettingsResponse& operator=(const GetBusinessSettingsResponse& other) = default; // copy assignment
    GetBusinessSettingsResponse& operator=(GetBusinessSettingsResponse&& other) noexcept = default; // move assignment

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree() const;
    void fromPropertyTree(boost::property_tree::ptree const& pt);


    /////////////////////////////////////////////
    /// GetBusinessSettingsResponse members

    /// <summary>
    /// 
    /// </summary>
    ApiResponseStatusType getStatus() const;
    void setStatus(ApiResponseStatusType value);

    /// <summary>
    /// 
    /// </summary>
    GetBusinessSettingsInfoDTO getResult() const;
    void setResult(GetBusinessSettingsInfoDTO value);

protected:
    ApiResponseStatusType m_Status = ApiResponseStatusType{};
    GetBusinessSettingsInfoDTO m_Result;
};

std::vector<GetBusinessSettingsResponse> createGetBusinessSettingsResponseVectorFromJsonString(const std::string& json);

template<>
inline boost::property_tree::ptree toPt<GetBusinessSettingsResponse>(const GetBusinessSettingsResponse& val) {
    return val.toPropertyTree();
}

template<>
inline GetBusinessSettingsResponse fromPt<GetBusinessSettingsResponse>(const boost::property_tree::ptree& pt) {
    GetBusinessSettingsResponse ret;
    ret.fromPropertyTree(pt);
    return ret;
}

}
}
}
}

#endif /* GetBusinessSettingsResponse_H_ */
