/*
 * regional_model_info_dto.h
 *
 * Региональная информация.
 */

#ifndef _regional_model_info_dto_H_
#define _regional_model_info_dto_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct regional_model_info_dto_t regional_model_info_dto_t;

#include "currency_type.h"

// Enum  for regional_model_info_dto

typedef enum  { _api__regional_model_info_dto__NULL = 0, _api__regional_model_info_dto__RUR, _api__regional_model_info_dto__USD, _api__regional_model_info_dto__EUR, _api__regional_model_info_dto__UAH, _api__regional_model_info_dto__AUD, _api__regional_model_info_dto__GBP, _api__regional_model_info_dto__BYR, _api__regional_model_info_dto__BYN, _api__regional_model_info_dto__DKK, _api__regional_model_info_dto__ISK, _api__regional_model_info_dto__KZT, _api__regional_model_info_dto__CAD, _api__regional_model_info_dto__CNY, _api__regional_model_info_dto__NOK, _api__regional_model_info_dto__XDR, _api__regional_model_info_dto__SGD, _api__regional_model_info_dto___TRY, _api__regional_model_info_dto__SEK, _api__regional_model_info_dto__CHF, _api__regional_model_info_dto__JPY, _api__regional_model_info_dto__AZN, _api__regional_model_info_dto__ALL, _api__regional_model_info_dto__DZD, _api__regional_model_info_dto__AOA, _api__regional_model_info_dto__ARS, _api__regional_model_info_dto__AMD, _api__regional_model_info_dto__AFN, _api__regional_model_info_dto__BHD, _api__regional_model_info_dto__BGN, _api__regional_model_info_dto__BOB, _api__regional_model_info_dto__BWP, _api__regional_model_info_dto__BND, _api__regional_model_info_dto__BRL, _api__regional_model_info_dto__BIF, _api__regional_model_info_dto__HUF, _api__regional_model_info_dto__VEF, _api__regional_model_info_dto__KPW, _api__regional_model_info_dto__VND, _api__regional_model_info_dto__GMD, _api__regional_model_info_dto__GHS, _api__regional_model_info_dto__GNF, _api__regional_model_info_dto__HKD, _api__regional_model_info_dto__GEL, _api__regional_model_info_dto__AED, _api__regional_model_info_dto__EGP, _api__regional_model_info_dto__ZMK, _api__regional_model_info_dto__ILS, _api__regional_model_info_dto__INR, _api__regional_model_info_dto__IDR, _api__regional_model_info_dto__JOD, _api__regional_model_info_dto__IQD, _api__regional_model_info_dto__IRR, _api__regional_model_info_dto__YER, _api__regional_model_info_dto__QAR, _api__regional_model_info_dto__KES, _api__regional_model_info_dto__KGS, _api__regional_model_info_dto__COP, _api__regional_model_info_dto__CDF, _api__regional_model_info_dto__CRC, _api__regional_model_info_dto__KWD, _api__regional_model_info_dto__CUP, _api__regional_model_info_dto__LAK, _api__regional_model_info_dto__LVL, _api__regional_model_info_dto__SLL, _api__regional_model_info_dto__LBP, _api__regional_model_info_dto__LYD, _api__regional_model_info_dto__SZL, _api__regional_model_info_dto__LTL, _api__regional_model_info_dto__MUR, _api__regional_model_info_dto__MRO, _api__regional_model_info_dto__MKD, _api__regional_model_info_dto__MWK, _api__regional_model_info_dto__MGA, _api__regional_model_info_dto__MYR, _api__regional_model_info_dto__MAD, _api__regional_model_info_dto__MXN, _api__regional_model_info_dto__MZN, _api__regional_model_info_dto__MDL, _api__regional_model_info_dto__MNT, _api__regional_model_info_dto__NPR, _api__regional_model_info_dto__NGN, _api__regional_model_info_dto__NIO, _api__regional_model_info_dto__NZD, _api__regional_model_info_dto__OMR, _api__regional_model_info_dto__PKR, _api__regional_model_info_dto__PYG, _api__regional_model_info_dto__PEN, _api__regional_model_info_dto__PLN, _api__regional_model_info_dto__KHR, _api__regional_model_info_dto__SAR, _api__regional_model_info_dto__RON, _api__regional_model_info_dto__SCR, _api__regional_model_info_dto__SYP, _api__regional_model_info_dto__SKK, _api__regional_model_info_dto__SOS, _api__regional_model_info_dto__SDG, _api__regional_model_info_dto__SRD, _api__regional_model_info_dto__TJS, _api__regional_model_info_dto__THB, _api__regional_model_info_dto__TWD, _api__regional_model_info_dto__BDT, _api__regional_model_info_dto__TZS, _api__regional_model_info_dto__TND, _api__regional_model_info_dto__TMM, _api__regional_model_info_dto__UGX, _api__regional_model_info_dto__UZS, _api__regional_model_info_dto__UYU, _api__regional_model_info_dto__PHP, _api__regional_model_info_dto__DJF, _api__regional_model_info_dto__XAF, _api__regional_model_info_dto__XOF, _api__regional_model_info_dto__HRK, _api__regional_model_info_dto__CZK, _api__regional_model_info_dto__CLP, _api__regional_model_info_dto__LKR, _api__regional_model_info_dto__EEK, _api__regional_model_info_dto__ETB, _api__regional_model_info_dto__RSD, _api__regional_model_info_dto__ZAR, _api__regional_model_info_dto__KRW, _api__regional_model_info_dto__NAD, _api__regional_model_info_dto__TL, _api__regional_model_info_dto__UE } _api__regional_model_info_dto__e;

char* regional_model_info_dto_currency_ToString(_api__regional_model_info_dto__e currency);

_api__regional_model_info_dto__e regional_model_info_dto_currency_FromString(char* currency);



typedef struct regional_model_info_dto_t {
    currency_type_t *currency; // custom
    long region_id; //numeric

} regional_model_info_dto_t;

regional_model_info_dto_t *regional_model_info_dto_create(
    currency_type_t *currency,
    long region_id
);

void regional_model_info_dto_free(regional_model_info_dto_t *regional_model_info_dto);

regional_model_info_dto_t *regional_model_info_dto_parseFromJSON(cJSON *regional_model_info_dtoJSON);

cJSON *regional_model_info_dto_convertToJSON(regional_model_info_dto_t *regional_model_info_dto);

#endif /* _regional_model_info_dto_H_ */

