/*
 * update_order_status_dto.h
 *
 * Список заказов.
 */

#ifndef _update_order_status_dto_H_
#define _update_order_status_dto_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct update_order_status_dto_t update_order_status_dto_t;

#include "order_status_type.h"
#include "order_substatus_type.h"
#include "order_update_status_type.h"

// Enum  for update_order_status_dto

typedef enum  { _api__update_order_status_dto__NULL = 0, _api__update_order_status_dto__PLACING, _api__update_order_status_dto__RESERVED, _api__update_order_status_dto__UNPAID, _api__update_order_status_dto__PROCESSING, _api__update_order_status_dto__DELIVERY, _api__update_order_status_dto__PICKUP, _api__update_order_status_dto__DELIVERED, _api__update_order_status_dto__CANCELLED, _api__update_order_status_dto__PENDING, _api__update_order_status_dto__PARTIALLY_RETURNED, _api__update_order_status_dto__RETURNED, _api__update_order_status_dto__UNKNOWN } _api__update_order_status_dto__e;

char* update_order_status_dto_status_ToString(_api__update_order_status_dto__e status);

_api__update_order_status_dto__e update_order_status_dto_status_FromString(char* status);

// Enum  for update_order_status_dto

typedef enum  { _api__update_order_status_dto__NULL = 0, _api__update_order_status_dto__RESERVATION_EXPIRED, _api__update_order_status_dto__USER_NOT_PAID, _api__update_order_status_dto__USER_UNREACHABLE, _api__update_order_status_dto__USER_CHANGED_MIND, _api__update_order_status_dto__USER_REFUSED_DELIVERY, _api__update_order_status_dto__USER_REFUSED_PRODUCT, _api__update_order_status_dto__SHOP_FAILED, _api__update_order_status_dto__USER_REFUSED_QUALITY, _api__update_order_status_dto__REPLACING_ORDER, _api__update_order_status_dto__PROCESSING_EXPIRED, _api__update_order_status_dto__PENDING_EXPIRED, _api__update_order_status_dto__SHOP_PENDING_CANCELLED, _api__update_order_status_dto__PENDING_CANCELLED, _api__update_order_status_dto__USER_FRAUD, _api__update_order_status_dto__RESERVATION_FAILED, _api__update_order_status_dto__USER_PLACED_OTHER_ORDER, _api__update_order_status_dto__USER_BOUGHT_CHEAPER, _api__update_order_status_dto__MISSING_ITEM, _api__update_order_status_dto__BROKEN_ITEM, _api__update_order_status_dto__WRONG_ITEM, _api__update_order_status_dto__PICKUP_EXPIRED, _api__update_order_status_dto__DELIVERY_PROBLEMS, _api__update_order_status_dto__LATE_CONTACT, _api__update_order_status_dto__CUSTOM, _api__update_order_status_dto__DELIVERY_SERVICE_FAILED, _api__update_order_status_dto__WAREHOUSE_FAILED_TO_SHIP, _api__update_order_status_dto__DELIVERY_SERIVCE_UNDELIVERED, _api__update_order_status_dto__DELIVERY_SERVICE_UNDELIVERED, _api__update_order_status_dto__PREORDER, _api__update_order_status_dto__AWAIT_CONFIRMATION, _api__update_order_status_dto__STARTED, _api__update_order_status_dto__PACKAGING, _api__update_order_status_dto__READY_TO_SHIP, _api__update_order_status_dto__SHIPPED, _api__update_order_status_dto__ASYNC_PROCESSING, _api__update_order_status_dto__USER_REFUSED_TO_PROVIDE_PERSONAL_DATA, _api__update_order_status_dto__WAITING_USER_INPUT, _api__update_order_status_dto__WAITING_BANK_DECISION, _api__update_order_status_dto__BANK_REJECT_CREDIT_OFFER, _api__update_order_status_dto__CUSTOMER_REJECT_CREDIT_OFFER, _api__update_order_status_dto__CREDIT_OFFER_FAILED, _api__update_order_status_dto__AWAIT_DELIVERY_DATES_CONFIRMATION, _api__update_order_status_dto__SERVICE_FAULT, _api__update_order_status_dto__DELIVERY_SERVICE_RECEIVED, _api__update_order_status_dto__USER_RECEIVED, _api__update_order_status_dto__WAITING_FOR_STOCKS, _api__update_order_status_dto__AS_PART_OF_MULTI_ORDER, _api__update_order_status_dto__READY_FOR_LAST_MILE, _api__update_order_status_dto__LAST_MILE_STARTED, _api__update_order_status_dto__ANTIFRAUD, _api__update_order_status_dto__DELIVERY_USER_NOT_RECEIVED, _api__update_order_status_dto__DELIVERY_SERVICE_DELIVERED, _api__update_order_status_dto__DELIVERED_USER_NOT_RECEIVED, _api__update_order_status_dto__USER_WANTED_ANOTHER_PAYMENT_METHOD, _api__update_order_status_dto__USER_RECEIVED_TECHNICAL_ERROR, _api__update_order_status_dto__USER_FORGOT_TO_USE_BONUS, _api__update_order_status_dto__RECEIVED_ON_DISTRIBUTION_CENTER, _api__update_order_status_dto__DELIVERY_SERVICE_NOT_RECEIVED, _api__update_order_status_dto__DELIVERY_SERVICE_LOST, _api__update_order_status_dto__SHIPPED_TO_WRONG_DELIVERY_SERVICE, _api__update_order_status_dto__DELIVERED_USER_RECEIVED, _api__update_order_status_dto__WAITING_TINKOFF_DECISION, _api__update_order_status_dto__COURIER_SEARCH, _api__update_order_status_dto__COURIER_FOUND, _api__update_order_status_dto__COURIER_IN_TRANSIT_TO_SENDER, _api__update_order_status_dto__COURIER_ARRIVED_TO_SENDER, _api__update_order_status_dto__COURIER_RECEIVED, _api__update_order_status_dto__COURIER_NOT_FOUND, _api__update_order_status_dto__COURIER_NOT_DELIVER_ORDER, _api__update_order_status_dto__COURIER_RETURNS_ORDER, _api__update_order_status_dto__COURIER_RETURNED_ORDER, _api__update_order_status_dto__WAITING_USER_DELIVERY_INPUT, _api__update_order_status_dto__PICKUP_SERVICE_RECEIVED, _api__update_order_status_dto__PICKUP_USER_RECEIVED, _api__update_order_status_dto__CANCELLED_COURIER_NOT_FOUND, _api__update_order_status_dto__COURIER_NOT_COME_FOR_ORDER, _api__update_order_status_dto__DELIVERY_NOT_MANAGED_REGION, _api__update_order_status_dto__INCOMPLETE_CONTACT_INFORMATION, _api__update_order_status_dto__INCOMPLETE_MULTI_ORDER, _api__update_order_status_dto__INAPPROPRIATE_WEIGHT_SIZE, _api__update_order_status_dto__TECHNICAL_ERROR, _api__update_order_status_dto__SORTING_CENTER_LOST, _api__update_order_status_dto__COURIER_SEARCH_NOT_STARTED, _api__update_order_status_dto__LOST, _api__update_order_status_dto__AWAIT_PAYMENT, _api__update_order_status_dto__AWAIT_LAVKA_RESERVATION, _api__update_order_status_dto__USER_WANTS_TO_CHANGE_ADDRESS, _api__update_order_status_dto__FULL_NOT_RANSOM, _api__update_order_status_dto__PRESCRIPTION_MISMATCH, _api__update_order_status_dto__DROPOFF_LOST, _api__update_order_status_dto__DROPOFF_CLOSED, _api__update_order_status_dto__DELIVERY_TO_STORE_STARTED, _api__update_order_status_dto__USER_WANTS_TO_CHANGE_DELIVERY_DATE, _api__update_order_status_dto__WRONG_ITEM_DELIVERED, _api__update_order_status_dto__DAMAGED_BOX, _api__update_order_status_dto__AWAIT_DELIVERY_DATES, _api__update_order_status_dto__LAST_MILE_COURIER_SEARCH, _api__update_order_status_dto__PICKUP_POINT_CLOSED, _api__update_order_status_dto__LEGAL_INFO_CHANGED, _api__update_order_status_dto__USER_HAS_NO_TIME_TO_PICKUP_ORDER, _api__update_order_status_dto__DELIVERY_CUSTOMS_ARRIVED, _api__update_order_status_dto__DELIVERY_CUSTOMS_CLEARED, _api__update_order_status_dto__FIRST_MILE_DELIVERY_SERVICE_RECEIVED, _api__update_order_status_dto__AWAIT_AUTO_DELIVERY_DATES, _api__update_order_status_dto__AWAIT_USER_PERSONAL_DATA, _api__update_order_status_dto__NO_PERSONAL_DATA_EXPIRED, _api__update_order_status_dto__CUSTOMS_PROBLEMS, _api__update_order_status_dto__AWAIT_CASHIER, _api__update_order_status_dto__WAITING_POSTPAID_BUDGET_RESERVATION, _api__update_order_status_dto__AWAIT_SERVICEABLE_CONFIRMATION, _api__update_order_status_dto__POSTPAID_BUDGET_RESERVATION_FAILED, _api__update_order_status_dto__AWAIT_CUSTOM_PRICE_CONFIRMATION, _api__update_order_status_dto__READY_FOR_PICKUP, _api__update_order_status_dto__UNKNOWN } _api__update_order_status_dto__e;

char* update_order_status_dto_substatus_ToString(_api__update_order_status_dto__e substatus);

_api__update_order_status_dto__e update_order_status_dto_substatus_FromString(char* substatus);

// Enum  for update_order_status_dto

typedef enum  { _api__update_order_status_dto__NULL = 0, _api__update_order_status_dto__OK, _api__update_order_status_dto__ERROR } _api__update_order_status_dto__e;

char* update_order_status_dto_update_status_ToString(_api__update_order_status_dto__e update_status);

_api__update_order_status_dto__e update_order_status_dto_update_status_FromString(char* update_status);



typedef struct update_order_status_dto_t {
    long id; //numeric
    order_status_type_t *status; // custom
    order_substatus_type_t *substatus; // custom
    order_update_status_type_t *update_status; // custom
    char *error_details; // string

} update_order_status_dto_t;

update_order_status_dto_t *update_order_status_dto_create(
    long id,
    order_status_type_t *status,
    order_substatus_type_t *substatus,
    order_update_status_type_t *update_status,
    char *error_details
);

void update_order_status_dto_free(update_order_status_dto_t *update_order_status_dto);

update_order_status_dto_t *update_order_status_dto_parseFromJSON(cJSON *update_order_status_dtoJSON);

cJSON *update_order_status_dto_convertToJSON(update_order_status_dto_t *update_order_status_dto);

#endif /* _update_order_status_dto_H_ */

