/*
 * update_price_with_discount_dto.h
 *
 * Цена с указанием скидки.
 */

#ifndef _update_price_with_discount_dto_H_
#define _update_price_with_discount_dto_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct update_price_with_discount_dto_t update_price_with_discount_dto_t;

#include "currency_type.h"

// Enum  for update_price_with_discount_dto

typedef enum  { _api__update_price_with_discount_dto__NULL = 0, _api__update_price_with_discount_dto__RUR, _api__update_price_with_discount_dto__USD, _api__update_price_with_discount_dto__EUR, _api__update_price_with_discount_dto__UAH, _api__update_price_with_discount_dto__AUD, _api__update_price_with_discount_dto__GBP, _api__update_price_with_discount_dto__BYR, _api__update_price_with_discount_dto__BYN, _api__update_price_with_discount_dto__DKK, _api__update_price_with_discount_dto__ISK, _api__update_price_with_discount_dto__KZT, _api__update_price_with_discount_dto__CAD, _api__update_price_with_discount_dto__CNY, _api__update_price_with_discount_dto__NOK, _api__update_price_with_discount_dto__XDR, _api__update_price_with_discount_dto__SGD, _api__update_price_with_discount_dto___TRY, _api__update_price_with_discount_dto__SEK, _api__update_price_with_discount_dto__CHF, _api__update_price_with_discount_dto__JPY, _api__update_price_with_discount_dto__AZN, _api__update_price_with_discount_dto__ALL, _api__update_price_with_discount_dto__DZD, _api__update_price_with_discount_dto__AOA, _api__update_price_with_discount_dto__ARS, _api__update_price_with_discount_dto__AMD, _api__update_price_with_discount_dto__AFN, _api__update_price_with_discount_dto__BHD, _api__update_price_with_discount_dto__BGN, _api__update_price_with_discount_dto__BOB, _api__update_price_with_discount_dto__BWP, _api__update_price_with_discount_dto__BND, _api__update_price_with_discount_dto__BRL, _api__update_price_with_discount_dto__BIF, _api__update_price_with_discount_dto__HUF, _api__update_price_with_discount_dto__VEF, _api__update_price_with_discount_dto__KPW, _api__update_price_with_discount_dto__VND, _api__update_price_with_discount_dto__GMD, _api__update_price_with_discount_dto__GHS, _api__update_price_with_discount_dto__GNF, _api__update_price_with_discount_dto__HKD, _api__update_price_with_discount_dto__GEL, _api__update_price_with_discount_dto__AED, _api__update_price_with_discount_dto__EGP, _api__update_price_with_discount_dto__ZMK, _api__update_price_with_discount_dto__ILS, _api__update_price_with_discount_dto__INR, _api__update_price_with_discount_dto__IDR, _api__update_price_with_discount_dto__JOD, _api__update_price_with_discount_dto__IQD, _api__update_price_with_discount_dto__IRR, _api__update_price_with_discount_dto__YER, _api__update_price_with_discount_dto__QAR, _api__update_price_with_discount_dto__KES, _api__update_price_with_discount_dto__KGS, _api__update_price_with_discount_dto__COP, _api__update_price_with_discount_dto__CDF, _api__update_price_with_discount_dto__CRC, _api__update_price_with_discount_dto__KWD, _api__update_price_with_discount_dto__CUP, _api__update_price_with_discount_dto__LAK, _api__update_price_with_discount_dto__LVL, _api__update_price_with_discount_dto__SLL, _api__update_price_with_discount_dto__LBP, _api__update_price_with_discount_dto__LYD, _api__update_price_with_discount_dto__SZL, _api__update_price_with_discount_dto__LTL, _api__update_price_with_discount_dto__MUR, _api__update_price_with_discount_dto__MRO, _api__update_price_with_discount_dto__MKD, _api__update_price_with_discount_dto__MWK, _api__update_price_with_discount_dto__MGA, _api__update_price_with_discount_dto__MYR, _api__update_price_with_discount_dto__MAD, _api__update_price_with_discount_dto__MXN, _api__update_price_with_discount_dto__MZN, _api__update_price_with_discount_dto__MDL, _api__update_price_with_discount_dto__MNT, _api__update_price_with_discount_dto__NPR, _api__update_price_with_discount_dto__NGN, _api__update_price_with_discount_dto__NIO, _api__update_price_with_discount_dto__NZD, _api__update_price_with_discount_dto__OMR, _api__update_price_with_discount_dto__PKR, _api__update_price_with_discount_dto__PYG, _api__update_price_with_discount_dto__PEN, _api__update_price_with_discount_dto__PLN, _api__update_price_with_discount_dto__KHR, _api__update_price_with_discount_dto__SAR, _api__update_price_with_discount_dto__RON, _api__update_price_with_discount_dto__SCR, _api__update_price_with_discount_dto__SYP, _api__update_price_with_discount_dto__SKK, _api__update_price_with_discount_dto__SOS, _api__update_price_with_discount_dto__SDG, _api__update_price_with_discount_dto__SRD, _api__update_price_with_discount_dto__TJS, _api__update_price_with_discount_dto__THB, _api__update_price_with_discount_dto__TWD, _api__update_price_with_discount_dto__BDT, _api__update_price_with_discount_dto__TZS, _api__update_price_with_discount_dto__TND, _api__update_price_with_discount_dto__TMM, _api__update_price_with_discount_dto__UGX, _api__update_price_with_discount_dto__UZS, _api__update_price_with_discount_dto__UYU, _api__update_price_with_discount_dto__PHP, _api__update_price_with_discount_dto__DJF, _api__update_price_with_discount_dto__XAF, _api__update_price_with_discount_dto__XOF, _api__update_price_with_discount_dto__HRK, _api__update_price_with_discount_dto__CZK, _api__update_price_with_discount_dto__CLP, _api__update_price_with_discount_dto__LKR, _api__update_price_with_discount_dto__EEK, _api__update_price_with_discount_dto__ETB, _api__update_price_with_discount_dto__RSD, _api__update_price_with_discount_dto__ZAR, _api__update_price_with_discount_dto__KRW, _api__update_price_with_discount_dto__NAD, _api__update_price_with_discount_dto__TL, _api__update_price_with_discount_dto__UE } _api__update_price_with_discount_dto__e;

char* update_price_with_discount_dto_currency_id_ToString(_api__update_price_with_discount_dto__e currency_id);

_api__update_price_with_discount_dto__e update_price_with_discount_dto_currency_id_FromString(char* currency_id);



typedef struct update_price_with_discount_dto_t {
    double value; //numeric
    currency_type_t *currency_id; // custom
    double discount_base; //numeric

} update_price_with_discount_dto_t;

update_price_with_discount_dto_t *update_price_with_discount_dto_create(
    double value,
    currency_type_t *currency_id,
    double discount_base
);

void update_price_with_discount_dto_free(update_price_with_discount_dto_t *update_price_with_discount_dto);

update_price_with_discount_dto_t *update_price_with_discount_dto_parseFromJSON(cJSON *update_price_with_discount_dtoJSON);

cJSON *update_price_with_discount_dto_convertToJSON(update_price_with_discount_dto_t *update_price_with_discount_dto);

#endif /* _update_price_with_discount_dto_H_ */

