/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.server.model;

import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelOfferDTO
 */
class ModelOfferDTOTest {
    private final ModelOfferDTO model = new ModelOfferDTO();

    /**
     * Model tests for ModelOfferDTO
     */
    @Test
    void testModelOfferDTO() {
        // TODO: test ModelOfferDTO
    }

    /**
     * Test the property 'discount'
     */
    @Test
    void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pos'
     */
    @Test
    void posTest() {
        // TODO: test pos
    }

    /**
     * Test the property 'preDiscountPrice'
     */
    @Test
    void preDiscountPriceTest() {
        // TODO: test preDiscountPrice
    }

    /**
     * Test the property 'price'
     */
    @Test
    void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'regionId'
     */
    @Test
    void regionIdTest() {
        // TODO: test regionId
    }

    /**
     * Test the property 'shippingCost'
     */
    @Test
    void shippingCostTest() {
        // TODO: test shippingCost
    }

    /**
     * Test the property 'shopName'
     */
    @Test
    void shopNameTest() {
        // TODO: test shopName
    }

    /**
     * Test the property 'shopRating'
     */
    @Test
    void shopRatingTest() {
        // TODO: test shopRating
    }

    /**
     * Test the property 'inStock'
     */
    @Test
    void inStockTest() {
        // TODO: test inStock
    }

}
