# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ympa_python_pydantic_v1_client.models.get_orders_stats_request import GetOrdersStatsRequest  # noqa: E501

class TestGetOrdersStatsRequest(unittest.TestCase):
    """GetOrdersStatsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrdersStatsRequest:
        """Test GetOrdersStatsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrdersStatsRequest`
        """
        model = GetOrdersStatsRequest()  # noqa: E501
        if include_optional:
            return GetOrdersStatsRequest(
                date_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                update_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                update_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                orders = [
                    56
                    ],
                statuses = [
                    'CANCELLED_BEFORE_PROCESSING'
                    ],
                has_cis = True
            )
        else:
            return GetOrdersStatsRequest(
        )
        """

    def testGetOrdersStatsRequest(self):
        """Test GetOrdersStatsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
