# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, conlist
from ympa_python_pydantic_v1_client.models.order_courier_dto import OrderCourierDTO
from ympa_python_pydantic_v1_client.models.order_delivery_address_dto import OrderDeliveryAddressDTO
from ympa_python_pydantic_v1_client.models.order_delivery_dates_dto import OrderDeliveryDatesDTO
from ympa_python_pydantic_v1_client.models.order_delivery_dispatch_type import OrderDeliveryDispatchType
from ympa_python_pydantic_v1_client.models.order_delivery_eac_type import OrderDeliveryEacType
from ympa_python_pydantic_v1_client.models.order_delivery_partner_type import OrderDeliveryPartnerType
from ympa_python_pydantic_v1_client.models.order_delivery_type import OrderDeliveryType
from ympa_python_pydantic_v1_client.models.order_lift_type import OrderLiftType
from ympa_python_pydantic_v1_client.models.order_shipment_dto import OrderShipmentDTO
from ympa_python_pydantic_v1_client.models.order_track_dto import OrderTrackDTO
from ympa_python_pydantic_v1_client.models.order_vat_type import OrderVatType
from ympa_python_pydantic_v1_client.models.region_dto import RegionDTO

class OrderDeliveryDTO(BaseModel):
    """
    Информация о доставке.  # noqa: E501
    """
    id: Optional[StrictStr] = Field(default=None, description="Идентификатор доставки, присвоенный магазином.  Указывается, только если магазин передал данный идентификатор в ответе на запрос методом [POST cart](../../pushapi/reference/cart.md). ")
    type: Optional[OrderDeliveryType] = None
    service_name: Optional[StrictStr] = Field(default=None, alias="serviceName", description="Наименование службы доставки.")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="{% note warning \"\" %}  Этот параметр устарел. Стоимость доставки смотрите в параметре `deliveryTotal`.  {% endnote %}  Стоимость доставки в валюте заказа. ")
    delivery_partner_type: Optional[OrderDeliveryPartnerType] = Field(default=None, alias="deliveryPartnerType")
    courier: Optional[OrderCourierDTO] = None
    dates: Optional[OrderDeliveryDatesDTO] = None
    region: Optional[RegionDTO] = None
    address: Optional[OrderDeliveryAddressDTO] = None
    vat: Optional[OrderVatType] = None
    delivery_service_id: Optional[StrictInt] = Field(default=None, alias="deliveryServiceId", description="Идентификатор службы доставки.")
    lift_type: Optional[OrderLiftType] = Field(default=None, alias="liftType")
    lift_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="liftPrice", description="Стоимость подъема на этаж.")
    outlet_code: Optional[StrictStr] = Field(default=None, alias="outletCode", description="Идентификатор пункта самовывоза, присвоенный магазином.")
    outlet_storage_limit_date: Optional[StrictStr] = Field(default=None, alias="outletStorageLimitDate", description="Формат даты: `ДД-ММ-ГГГГ`. ")
    dispatch_type: Optional[OrderDeliveryDispatchType] = Field(default=None, alias="dispatchType")
    tracks: Optional[conlist(OrderTrackDTO)] = Field(default=None, description="Информация для отслеживания перемещений посылки.")
    shipments: Optional[conlist(OrderShipmentDTO)] = Field(default=None, description="Информация о посылках.")
    estimated: Optional[StrictBool] = Field(default=None, description="Приблизительная ли дата доставки.")
    eac_type: Optional[OrderDeliveryEacType] = Field(default=None, alias="eacType")
    eac_code: Optional[StrictStr] = Field(default=None, alias="eacCode", description="Код подтверждения ЭАПП (для типа `MERCHANT_TO_COURIER`). ")
    __properties = ["id", "type", "serviceName", "price", "deliveryPartnerType", "courier", "dates", "region", "address", "vat", "deliveryServiceId", "liftType", "liftPrice", "outletCode", "outletStorageLimitDate", "dispatchType", "tracks", "shipments", "estimated", "eacType", "eacCode"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OrderDeliveryDTO:
        """Create an instance of OrderDeliveryDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of courier
        if self.courier:
            _dict['courier'] = self.courier.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dates
        if self.dates:
            _dict['dates'] = self.dates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of region
        if self.region:
            _dict['region'] = self.region.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tracks (list)
        _items = []
        if self.tracks:
            for _item in self.tracks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tracks'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in shipments (list)
        _items = []
        if self.shipments:
            for _item in self.shipments:
                if _item:
                    _items.append(_item.to_dict())
            _dict['shipments'] = _items
        # set to None if tracks (nullable) is None
        # and __fields_set__ contains the field
        if self.tracks is None and "tracks" in self.__fields_set__:
            _dict['tracks'] = None

        # set to None if shipments (nullable) is None
        # and __fields_set__ contains the field
        if self.shipments is None and "shipments" in self.__fields_set__:
            _dict['shipments'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OrderDeliveryDTO:
        """Create an instance of OrderDeliveryDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OrderDeliveryDTO.parse_obj(obj)

        _obj = OrderDeliveryDTO.parse_obj({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "service_name": obj.get("serviceName"),
            "price": obj.get("price"),
            "delivery_partner_type": obj.get("deliveryPartnerType"),
            "courier": OrderCourierDTO.from_dict(obj.get("courier")) if obj.get("courier") is not None else None,
            "dates": OrderDeliveryDatesDTO.from_dict(obj.get("dates")) if obj.get("dates") is not None else None,
            "region": RegionDTO.from_dict(obj.get("region")) if obj.get("region") is not None else None,
            "address": OrderDeliveryAddressDTO.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "vat": obj.get("vat"),
            "delivery_service_id": obj.get("deliveryServiceId"),
            "lift_type": obj.get("liftType"),
            "lift_price": obj.get("liftPrice"),
            "outlet_code": obj.get("outletCode"),
            "outlet_storage_limit_date": obj.get("outletStorageLimitDate"),
            "dispatch_type": obj.get("dispatchType"),
            "tracks": [OrderTrackDTO.from_dict(_item) for _item in obj.get("tracks")] if obj.get("tracks") is not None else None,
            "shipments": [OrderShipmentDTO.from_dict(_item) for _item in obj.get("shipments")] if obj.get("shipments") is not None else None,
            "estimated": obj.get("estimated"),
            "eac_type": obj.get("eacType"),
            "eac_code": obj.get("eacCode")
        })
        return _obj


