/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ympa_csharp_client.Client.OpenAPIDateConverter;

namespace ympa_csharp_client.Model
{
    /// <summary>
    /// Информация об отгрузках.
    /// </summary>
    [DataContract(Name = "SearchShipmentsResponseDTO")]
    public partial class SearchShipmentsResponseDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchShipmentsResponseDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchShipmentsResponseDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchShipmentsResponseDTO" /> class.
        /// </summary>
        /// <param name="shipments">Список с информацией об отгрузках. (required).</param>
        /// <param name="paging">paging.</param>
        public SearchShipmentsResponseDTO(List<ShipmentInfoDTO> shipments = default(List<ShipmentInfoDTO>), ForwardScrollingPagerDTO paging = default(ForwardScrollingPagerDTO))
        {
            // to ensure "shipments" is required (not null)
            if (shipments == null)
            {
                throw new ArgumentNullException("shipments is a required property for SearchShipmentsResponseDTO and cannot be null");
            }
            this.Shipments = shipments;
            this.Paging = paging;
        }

        /// <summary>
        /// Список с информацией об отгрузках.
        /// </summary>
        /// <value>Список с информацией об отгрузках.</value>
        [DataMember(Name = "shipments", IsRequired = true, EmitDefaultValue = true)]
        public List<ShipmentInfoDTO> Shipments { get; set; }

        /// <summary>
        /// Gets or Sets Paging
        /// </summary>
        [DataMember(Name = "paging", EmitDefaultValue = false)]
        public ForwardScrollingPagerDTO Paging { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchShipmentsResponseDTO {\n");
            sb.Append("  Shipments: ").Append(Shipments).Append("\n");
            sb.Append("  Paging: ").Append(Paging).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
