/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ympa_csharp_client.Client.OpenAPIDateConverter;

namespace ympa_csharp_client.Model
{
    /// <summary>
    /// Информация об остатках товаров на складе.
    /// </summary>
    [DataContract(Name = "WarehouseOffersDTO")]
    public partial class WarehouseOffersDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WarehouseOffersDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WarehouseOffersDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WarehouseOffersDTO" /> class.
        /// </summary>
        /// <param name="warehouseId">Идентификатор склада. (required).</param>
        /// <param name="offers">Информация об остатках. (required).</param>
        public WarehouseOffersDTO(long warehouseId = default(long), List<WarehouseOfferDTO> offers = default(List<WarehouseOfferDTO>))
        {
            this.WarehouseId = warehouseId;
            // to ensure "offers" is required (not null)
            if (offers == null)
            {
                throw new ArgumentNullException("offers is a required property for WarehouseOffersDTO and cannot be null");
            }
            this.Offers = offers;
        }

        /// <summary>
        /// Идентификатор склада.
        /// </summary>
        /// <value>Идентификатор склада.</value>
        [DataMember(Name = "warehouseId", IsRequired = true, EmitDefaultValue = true)]
        public long WarehouseId { get; set; }

        /// <summary>
        /// Информация об остатках.
        /// </summary>
        /// <value>Информация об остатках.</value>
        [DataMember(Name = "offers", IsRequired = true, EmitDefaultValue = true)]
        public List<WarehouseOfferDTO> Offers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WarehouseOffersDTO {\n");
            sb.Append("  WarehouseId: ").Append(WarehouseId).Append("\n");
            sb.Append("  Offers: ").Append(Offers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
