import {interfaces} from 'inversify';

import { BidsService } from './api/bids.service';
import { BusinessOfferMappingsService } from './api/businessOfferMappings.service';
import { BusinessesService } from './api/businesses.service';
import { CampaignsService } from './api/campaigns.service';
import { CategoriesService } from './api/categories.service';
import { ChatsService } from './api/chats.service';
import { ContentService } from './api/content.service';
import { DbsService } from './api/dbs.service';
import { DeliveryServicesService } from './api/deliveryServices.service';
import { ExpressService } from './api/express.service';
import { FbsService } from './api/fbs.service';
import { FbyService } from './api/fby.service';
import { FeedbacksService } from './api/feedbacks.service';
import { FeedsService } from './api/feeds.service';
import { GoodsFeedbackService } from './api/goodsFeedback.service';
import { GoodsStatsService } from './api/goodsStats.service';
import { HiddenOffersService } from './api/hiddenOffers.service';
import { ModelsService } from './api/models.service';
import { OfferMappingsService } from './api/offerMappings.service';
import { OffersService } from './api/offers.service';
import { OrderBusinessInformationService } from './api/orderBusinessInformation.service';
import { OrderDeliveryService } from './api/orderDelivery.service';
import { OrderLabelsService } from './api/orderLabels.service';
import { OrdersService } from './api/orders.service';
import { OrdersStatsService } from './api/ordersStats.service';
import { OutletLicensesService } from './api/outletLicenses.service';
import { OutletsService } from './api/outlets.service';
import { PriceQuarantineService } from './api/priceQuarantine.service';
import { PricesService } from './api/prices.service';
import { PromosService } from './api/promos.service';
import { RatingsService } from './api/ratings.service';
import { RegionsService } from './api/regions.service';
import { ReportsService } from './api/reports.service';
import { ReturnsService } from './api/returns.service';
import { ShipmentsService } from './api/shipments.service';
import { StocksService } from './api/stocks.service';
import { TariffsService } from './api/tariffs.service';
import { WarehousesService } from './api/warehouses.service';

export class ApiServiceBinder {
    public static with(container: interfaces.Container) {
        container.bind<BidsService>('BidsService').to(BidsService).inSingletonScope();
        container.bind<BusinessOfferMappingsService>('BusinessOfferMappingsService').to(BusinessOfferMappingsService).inSingletonScope();
        container.bind<BusinessesService>('BusinessesService').to(BusinessesService).inSingletonScope();
        container.bind<CampaignsService>('CampaignsService').to(CampaignsService).inSingletonScope();
        container.bind<CategoriesService>('CategoriesService').to(CategoriesService).inSingletonScope();
        container.bind<ChatsService>('ChatsService').to(ChatsService).inSingletonScope();
        container.bind<ContentService>('ContentService').to(ContentService).inSingletonScope();
        container.bind<DbsService>('DbsService').to(DbsService).inSingletonScope();
        container.bind<DeliveryServicesService>('DeliveryServicesService').to(DeliveryServicesService).inSingletonScope();
        container.bind<ExpressService>('ExpressService').to(ExpressService).inSingletonScope();
        container.bind<FbsService>('FbsService').to(FbsService).inSingletonScope();
        container.bind<FbyService>('FbyService').to(FbyService).inSingletonScope();
        container.bind<FeedbacksService>('FeedbacksService').to(FeedbacksService).inSingletonScope();
        container.bind<FeedsService>('FeedsService').to(FeedsService).inSingletonScope();
        container.bind<GoodsFeedbackService>('GoodsFeedbackService').to(GoodsFeedbackService).inSingletonScope();
        container.bind<GoodsStatsService>('GoodsStatsService').to(GoodsStatsService).inSingletonScope();
        container.bind<HiddenOffersService>('HiddenOffersService').to(HiddenOffersService).inSingletonScope();
        container.bind<ModelsService>('ModelsService').to(ModelsService).inSingletonScope();
        container.bind<OfferMappingsService>('OfferMappingsService').to(OfferMappingsService).inSingletonScope();
        container.bind<OffersService>('OffersService').to(OffersService).inSingletonScope();
        container.bind<OrderBusinessInformationService>('OrderBusinessInformationService').to(OrderBusinessInformationService).inSingletonScope();
        container.bind<OrderDeliveryService>('OrderDeliveryService').to(OrderDeliveryService).inSingletonScope();
        container.bind<OrderLabelsService>('OrderLabelsService').to(OrderLabelsService).inSingletonScope();
        container.bind<OrdersService>('OrdersService').to(OrdersService).inSingletonScope();
        container.bind<OrdersStatsService>('OrdersStatsService').to(OrdersStatsService).inSingletonScope();
        container.bind<OutletLicensesService>('OutletLicensesService').to(OutletLicensesService).inSingletonScope();
        container.bind<OutletsService>('OutletsService').to(OutletsService).inSingletonScope();
        container.bind<PriceQuarantineService>('PriceQuarantineService').to(PriceQuarantineService).inSingletonScope();
        container.bind<PricesService>('PricesService').to(PricesService).inSingletonScope();
        container.bind<PromosService>('PromosService').to(PromosService).inSingletonScope();
        container.bind<RatingsService>('RatingsService').to(RatingsService).inSingletonScope();
        container.bind<RegionsService>('RegionsService').to(RegionsService).inSingletonScope();
        container.bind<ReportsService>('ReportsService').to(ReportsService).inSingletonScope();
        container.bind<ReturnsService>('ReturnsService').to(ReturnsService).inSingletonScope();
        container.bind<ShipmentsService>('ShipmentsService').to(ShipmentsService).inSingletonScope();
        container.bind<StocksService>('StocksService').to(StocksService).inSingletonScope();
        container.bind<TariffsService>('TariffsService').to(TariffsService).inSingletonScope();
        container.bind<WarehousesService>('WarehousesService').to(WarehousesService).inSingletonScope();
    }
}
