package org.openapitools.server.api.verticle;

import org.openapitools.server.api.model.ApiClientDataErrorResponse;
import org.openapitools.server.api.model.ApiForbiddenErrorResponse;
import org.openapitools.server.api.model.ApiLimitErrorResponse;
import org.openapitools.server.api.model.ApiNotFoundErrorResponse;
import org.openapitools.server.api.model.ApiServerErrorResponse;
import org.openapitools.server.api.model.ApiUnauthorizedErrorResponse;
import org.openapitools.server.api.model.ConfirmShipmentRequest;
import org.openapitools.server.api.model.EmptyApiResponse;
import java.io.File;
import org.openapitools.server.api.model.GetShipmentOrdersInfoResponse;
import org.openapitools.server.api.model.GetShipmentResponse;
import org.openapitools.server.api.MainApiException;
import org.openapitools.server.api.model.SearchShipmentsRequest;
import org.openapitools.server.api.model.SearchShipmentsResponse;
import org.openapitools.server.api.model.SetShipmentPalletsCountRequest;
import org.openapitools.server.api.model.ShipmentPalletLabelPageFormatType;
import org.openapitools.server.api.model.TransferOrdersFromShipmentRequest;

public final class ShipmentsApiException extends MainApiException {
    public ShipmentsApiException(int statusCode, String statusMessage) {
        super(statusCode, statusMessage);
    }

    public static final ShipmentsApiException Shipments_confirmShipment_200_Exception = new ShipmentsApiException(200, "Пустой ответ.");
    public static final ShipmentsApiException Shipments_confirmShipment_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_confirmShipment_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_confirmShipment_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_confirmShipment_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_confirmShipment_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_confirmShipment_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_downloadShipmentAct_200_Exception = new ShipmentsApiException(200, "Акт приема-передачи для отгрузки в формате PDF.");
    public static final ShipmentsApiException Shipments_downloadShipmentAct_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_downloadShipmentAct_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_downloadShipmentAct_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_downloadShipmentAct_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_downloadShipmentAct_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_downloadShipmentAct_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_downloadShipmentDiscrepancyAct_200_Exception = new ShipmentsApiException(200, "Акт расхождений в формате XLSX.");
    public static final ShipmentsApiException Shipments_downloadShipmentDiscrepancyAct_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_downloadShipmentDiscrepancyAct_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_downloadShipmentDiscrepancyAct_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_downloadShipmentDiscrepancyAct_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_downloadShipmentDiscrepancyAct_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_downloadShipmentDiscrepancyAct_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_downloadShipmentInboundAct_200_Exception = new ShipmentsApiException(200, "Акт в формате PDF.");
    public static final ShipmentsApiException Shipments_downloadShipmentInboundAct_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_downloadShipmentInboundAct_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_downloadShipmentInboundAct_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_downloadShipmentInboundAct_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_downloadShipmentInboundAct_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_downloadShipmentInboundAct_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_downloadShipmentPalletLabels_200_Exception = new ShipmentsApiException(200, "PDF‑файл с ярлыками на все упаковки в отгрузке.");
    public static final ShipmentsApiException Shipments_downloadShipmentPalletLabels_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_downloadShipmentPalletLabels_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_downloadShipmentPalletLabels_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_downloadShipmentPalletLabels_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_downloadShipmentPalletLabels_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_downloadShipmentPalletLabels_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_downloadShipmentReceptionTransferAct_200_Exception = new ShipmentsApiException(200, "Акт приема-передачи в формате PDF.");
    public static final ShipmentsApiException Shipments_downloadShipmentReceptionTransferAct_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_downloadShipmentReceptionTransferAct_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_downloadShipmentReceptionTransferAct_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_downloadShipmentReceptionTransferAct_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_downloadShipmentReceptionTransferAct_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_downloadShipmentReceptionTransferAct_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_downloadShipmentTransportationWaybill_200_Exception = new ShipmentsApiException(200, "Транспортная накладная в формате XLSX.");
    public static final ShipmentsApiException Shipments_downloadShipmentTransportationWaybill_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_downloadShipmentTransportationWaybill_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_downloadShipmentTransportationWaybill_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_downloadShipmentTransportationWaybill_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_downloadShipmentTransportationWaybill_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_downloadShipmentTransportationWaybill_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_getShipment_200_Exception = new ShipmentsApiException(200, "Найденная отгрузка.");
    public static final ShipmentsApiException Shipments_getShipment_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_getShipment_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_getShipment_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_getShipment_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_getShipment_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_getShipment_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_getShipmentOrdersInfo_200_Exception = new ShipmentsApiException(200, "Информация по годным/негодным для печати ярлыков заказам в отгрузке.");
    public static final ShipmentsApiException Shipments_getShipmentOrdersInfo_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_getShipmentOrdersInfo_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_getShipmentOrdersInfo_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_getShipmentOrdersInfo_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_getShipmentOrdersInfo_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_getShipmentOrdersInfo_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_searchShipments_200_Exception = new ShipmentsApiException(200, "Найденные отгрузки.");
    public static final ShipmentsApiException Shipments_searchShipments_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_searchShipments_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_searchShipments_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_searchShipments_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_searchShipments_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_searchShipments_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_setShipmentPalletsCount_200_Exception = new ShipmentsApiException(200, "Имеет значение только тип ответа. Если ответ `ОК`, количество упаковок записано.");
    public static final ShipmentsApiException Shipments_setShipmentPalletsCount_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_setShipmentPalletsCount_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_setShipmentPalletsCount_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_setShipmentPalletsCount_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_setShipmentPalletsCount_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_setShipmentPalletsCount_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    public static final ShipmentsApiException Shipments_transferOrdersFromShipment_200_Exception = new ShipmentsApiException(200, "Запрос на перенос заказов проверен и принят, и они будут перенесены спустя несколько минут.");
    public static final ShipmentsApiException Shipments_transferOrdersFromShipment_400_Exception = new ShipmentsApiException(400, "Запрос содержит неправильные данные.");
    public static final ShipmentsApiException Shipments_transferOrdersFromShipment_401_Exception = new ShipmentsApiException(401, "В запросе не указаны данные для авторизации.");
    public static final ShipmentsApiException Shipments_transferOrdersFromShipment_403_Exception = new ShipmentsApiException(403, "Данные для авторизации неверны или доступ к ресурсу запрещен.");
    public static final ShipmentsApiException Shipments_transferOrdersFromShipment_404_Exception = new ShipmentsApiException(404, "Запрашиваемый ресурс не найден.");
    public static final ShipmentsApiException Shipments_transferOrdersFromShipment_420_Exception = new ShipmentsApiException(420, "Превышено ограничение на доступ к ресурсу.");
    public static final ShipmentsApiException Shipments_transferOrdersFromShipment_500_Exception = new ShipmentsApiException(500, "Внутренняя ошибка сервера.");
    

}