#
# Партнерский API Маркета
# API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
# Version: LATEST
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Запрос на изменение информации по остаткам товаров.

.PARAMETER Skus
Данные об остатках товаров. 
.OUTPUTS

UpdateStocksRequest<PSCustomObject>
#>

function Initialize-UpdateStocksRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Skus}
    )

    Process {
        'Creating PSCustomObject: ympa_powershell_client => UpdateStocksRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Skus) {
            throw "invalid value for 'Skus', 'Skus' cannot be null."
        }

        if ($Skus.length -gt 2000) {
            throw "invalid value for 'Skus', number of items must be less than or equal to 2000."
        }

        if ($Skus.length -lt 1) {
            throw "invalid value for 'Skus', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "skus" = ${Skus}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UpdateStocksRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to UpdateStocksRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UpdateStocksRequest<PSCustomObject>
#>
function ConvertFrom-JsonToUpdateStocksRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ympa_powershell_client => UpdateStocksRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in UpdateStocksRequest
        $AllProperties = ("skus")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'skus' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "skus"))) {
            throw "Error! JSON cannot be serialized due to the required property 'skus' missing."
        } else {
            $Skus = $JsonParameters.PSobject.Properties["skus"].value
        }

        $PSO = [PSCustomObject]@{
            "skus" = ${Skus}
        }

        return $PSO
    }

}

