--[[
  Партнерский API Маркета

  API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

  The version of the OpenAPI document: LATEST
  
  Generated by: https://openapi-generator.tech
]]

-- order_business_documents_dto class
local order_business_documents_dto = {}
local order_business_documents_dto_mt = {
	__name = "order_business_documents_dto";
	__index = order_business_documents_dto;
}

local function cast_order_business_documents_dto(t)
	return setmetatable(t, order_business_documents_dto_mt)
end

local function new_order_business_documents_dto(upd, ukd, torg_twelve, sf, ksf)
	return cast_order_business_documents_dto({
		["upd"] = upd;
		["ukd"] = ukd;
		["torgTwelve"] = torg_twelve;
		["sf"] = sf;
		["ksf"] = ksf;
	})
end

return {
	cast = cast_order_business_documents_dto;
	new = new_order_business_documents_dto;
}
