--[[
  Партнерский API Маркета

  API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

  The version of the OpenAPI document: LATEST
  
  Generated by: https://openapi-generator.tech
]]

-- price_quarantine_verdict_parameter_dto class
local price_quarantine_verdict_parameter_dto = {}
local price_quarantine_verdict_parameter_dto_mt = {
	__name = "price_quarantine_verdict_parameter_dto";
	__index = price_quarantine_verdict_parameter_dto;
}

local function cast_price_quarantine_verdict_parameter_dto(t)
	return setmetatable(t, price_quarantine_verdict_parameter_dto_mt)
end

local function new_price_quarantine_verdict_parameter_dto(name, value)
	return cast_price_quarantine_verdict_parameter_dto({
		["name"] = name;
		["value"] = value;
	})
end

return {
	cast = cast_price_quarantine_verdict_parameter_dto;
	new = new_price_quarantine_verdict_parameter_dto;
}
