//
// OfferMappingEntryDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Список товаров.  
public struct OfferMappingEntryDTO: Codable {
    public var mapping: OfferMappingDTO?
    public var awaitingModerationMapping: OfferMappingDTO?
    public var rejectedMapping: OfferMappingDTO?
    public var offer: MappingsOfferDTO?

    public init(mapping: OfferMappingDTO? = nil, awaitingModerationMapping: OfferMappingDTO? = nil, rejectedMapping: OfferMappingDTO? = nil, offer: MappingsOfferDTO? = nil) {
        self.mapping = mapping
        self.awaitingModerationMapping = awaitingModerationMapping
        self.rejectedMapping = rejectedMapping
        self.offer = offer
    }
}
