//
// TariffParameterDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Детали расчета конкретной услуги Маркета. 
public struct TariffParameterDTO: Codable {
    /// Название параметра.
    public var name: String
    /// Значение параметра.
    public var value: String

    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }
}
