/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ympa_cpp_restsdk_client/model/AffectedOrderQualityRatingComponentType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("DBS_CANCELLATION_RATE")))
        return AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_DBS_CANCELLATION_RATE;
    if (val == utility::conversions::to_string_t(U("DBS_LATE_DELIVERY_RATE")))
        return AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_DBS_LATE_DELIVERY_RATE;
    if (val == utility::conversions::to_string_t(U("FBS_CANCELLATION_RATE")))
        return AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_FBS_CANCELLATION_RATE;
    if (val == utility::conversions::to_string_t(U("FBS_LATE_SHIP_RATE")))
        return AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_FBS_LATE_SHIP_RATE;
    return {};
}

EnumUnderlyingType fromEnum(AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType e)
{
    switch (e)
    {
    case AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_DBS_CANCELLATION_RATE:
        return U("DBS_CANCELLATION_RATE");
    case AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_DBS_LATE_DELIVERY_RATE:
        return U("DBS_LATE_DELIVERY_RATE");
    case AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_FBS_CANCELLATION_RATE:
        return U("FBS_CANCELLATION_RATE");
    case AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType_FBS_LATE_SHIP_RATE:
        return U("FBS_LATE_SHIP_RATE");
    default:
        break;
    }
    return {};
}
}

AffectedOrderQualityRatingComponentType::AffectedOrderQualityRatingComponentType()
{
}

AffectedOrderQualityRatingComponentType::~AffectedOrderQualityRatingComponentType()
{
}

void AffectedOrderQualityRatingComponentType::validate()
{
    // TODO: implement validation
}

web::json::value AffectedOrderQualityRatingComponentType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool AffectedOrderQualityRatingComponentType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void AffectedOrderQualityRatingComponentType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool AffectedOrderQualityRatingComponentType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType AffectedOrderQualityRatingComponentType::getValue() const
{
   return m_value;
}

void AffectedOrderQualityRatingComponentType::setValue(AffectedOrderQualityRatingComponentType::eAffectedOrderQualityRatingComponentType const value)
{
   m_value = value;
}


}
}
}
}


