/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ympa_cpp_restsdk_client/model/EacVerificationStatusType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

EacVerificationStatusType::eEacVerificationStatusType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("ACCEPTED")))
        return EacVerificationStatusType::eEacVerificationStatusType::EacVerificationStatusType_ACCEPTED;
    if (val == utility::conversions::to_string_t(U("REJECTED")))
        return EacVerificationStatusType::eEacVerificationStatusType::EacVerificationStatusType_REJECTED;
    if (val == utility::conversions::to_string_t(U("NEED_UPDATE")))
        return EacVerificationStatusType::eEacVerificationStatusType::EacVerificationStatusType_NEED_UPDATE;
    return {};
}

EnumUnderlyingType fromEnum(EacVerificationStatusType::eEacVerificationStatusType e)
{
    switch (e)
    {
    case EacVerificationStatusType::eEacVerificationStatusType::EacVerificationStatusType_ACCEPTED:
        return U("ACCEPTED");
    case EacVerificationStatusType::eEacVerificationStatusType::EacVerificationStatusType_REJECTED:
        return U("REJECTED");
    case EacVerificationStatusType::eEacVerificationStatusType::EacVerificationStatusType_NEED_UPDATE:
        return U("NEED_UPDATE");
    default:
        break;
    }
    return {};
}
}

EacVerificationStatusType::EacVerificationStatusType()
{
}

EacVerificationStatusType::~EacVerificationStatusType()
{
}

void EacVerificationStatusType::validate()
{
    // TODO: implement validation
}

web::json::value EacVerificationStatusType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool EacVerificationStatusType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void EacVerificationStatusType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool EacVerificationStatusType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

EacVerificationStatusType::eEacVerificationStatusType EacVerificationStatusType::getValue() const
{
   return m_value;
}

void EacVerificationStatusType::setValue(EacVerificationStatusType::eEacVerificationStatusType const value)
{
   m_value = value;
}


}
}
}
}


