/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ympa_cpp_restsdk_client/model/SearchShipmentsResponseDTO.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



SearchShipmentsResponseDTO::SearchShipmentsResponseDTO()
{
    m_ShipmentsIsSet = false;
    m_PagingIsSet = false;
}

SearchShipmentsResponseDTO::~SearchShipmentsResponseDTO()
{
}

void SearchShipmentsResponseDTO::validate()
{
    // TODO: implement validation
}

web::json::value SearchShipmentsResponseDTO::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ShipmentsIsSet)
    {
        val[utility::conversions::to_string_t(U("shipments"))] = ModelBase::toJson(m_Shipments);
    }
    if(m_PagingIsSet)
    {
        val[utility::conversions::to_string_t(U("paging"))] = ModelBase::toJson(m_Paging);
    }

    return val;
}

bool SearchShipmentsResponseDTO::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("shipments"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("shipments")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ShipmentInfoDTO>> refVal_setShipments;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShipments);
            setShipments(refVal_setShipments);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("paging"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("paging")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ForwardScrollingPagerDTO> refVal_setPaging;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaging);
            setPaging(refVal_setPaging);
        }
    }
    return ok;
}

void SearchShipmentsResponseDTO::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ShipmentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("shipments")), m_Shipments));
    }
    if(m_PagingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("paging")), m_Paging));
    }
}

bool SearchShipmentsResponseDTO::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("shipments"))))
    {
        std::vector<std::shared_ptr<ShipmentInfoDTO>> refVal_setShipments;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("shipments"))), refVal_setShipments );
        setShipments(refVal_setShipments);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("paging"))))
    {
        std::shared_ptr<ForwardScrollingPagerDTO> refVal_setPaging;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("paging"))), refVal_setPaging );
        setPaging(refVal_setPaging);
    }
    return ok;
}

std::vector<std::shared_ptr<ShipmentInfoDTO>>& SearchShipmentsResponseDTO::getShipments()
{
    return m_Shipments;
}

void SearchShipmentsResponseDTO::setShipments(const std::vector<std::shared_ptr<ShipmentInfoDTO>>& value)
{
    m_Shipments = value;
    m_ShipmentsIsSet = true;
}

bool SearchShipmentsResponseDTO::shipmentsIsSet() const
{
    return m_ShipmentsIsSet;
}

void SearchShipmentsResponseDTO::unsetShipments()
{
    m_ShipmentsIsSet = false;
}
std::shared_ptr<ForwardScrollingPagerDTO> SearchShipmentsResponseDTO::getPaging() const
{
    return m_Paging;
}

void SearchShipmentsResponseDTO::setPaging(const std::shared_ptr<ForwardScrollingPagerDTO>& value)
{
    m_Paging = value;
    m_PagingIsSet = true;
}

bool SearchShipmentsResponseDTO::pagingIsSet() const
{
    return m_PagingIsSet;
}

void SearchShipmentsResponseDTO::unsetPaging()
{
    m_PagingIsSet = false;
}
}
}
}
}


