from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ympa_python_flask_server.models.base_model import Model
from ympa_python_flask_server.models.api_response_status_type import ApiResponseStatusType
from ympa_python_flask_server.models.feed_index_logs_result_dto import FeedIndexLogsResultDTO
from ympa_python_flask_server import util

from ympa_python_flask_server.models.api_response_status_type import ApiResponseStatusType  # noqa: E501
from ympa_python_flask_server.models.feed_index_logs_result_dto import FeedIndexLogsResultDTO  # noqa: E501

class GetFeedIndexLogsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, result=None):  # noqa: E501
        """GetFeedIndexLogsResponse - a model defined in OpenAPI

        :param status: The status of this GetFeedIndexLogsResponse.  # noqa: E501
        :type status: ApiResponseStatusType
        :param result: The result of this GetFeedIndexLogsResponse.  # noqa: E501
        :type result: FeedIndexLogsResultDTO
        """
        self.openapi_types = {
            'status': ApiResponseStatusType,
            'result': FeedIndexLogsResultDTO
        }

        self.attribute_map = {
            'status': 'status',
            'result': 'result'
        }

        self._status = status
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'GetFeedIndexLogsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetFeedIndexLogsResponse of this GetFeedIndexLogsResponse.  # noqa: E501
        :rtype: GetFeedIndexLogsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> ApiResponseStatusType:
        """Gets the status of this GetFeedIndexLogsResponse.


        :return: The status of this GetFeedIndexLogsResponse.
        :rtype: ApiResponseStatusType
        """
        return self._status

    @status.setter
    def status(self, status: ApiResponseStatusType):
        """Sets the status of this GetFeedIndexLogsResponse.


        :param status: The status of this GetFeedIndexLogsResponse.
        :type status: ApiResponseStatusType
        """

        self._status = status

    @property
    def result(self) -> FeedIndexLogsResultDTO:
        """Gets the result of this GetFeedIndexLogsResponse.


        :return: The result of this GetFeedIndexLogsResponse.
        :rtype: FeedIndexLogsResultDTO
        """
        return self._result

    @result.setter
    def result(self, result: FeedIndexLogsResultDTO):
        """Sets the result of this GetFeedIndexLogsResponse.


        :param result: The result of this GetFeedIndexLogsResponse.
        :type result: FeedIndexLogsResultDTO
        """

        self._result = result
