/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * OpenAPI spec version: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIGoodsFeedbackStatisticsDTO
 *
 * Статистическая информация по отзыву.
 */
class OPENAPI_API OpenAPIGoodsFeedbackStatisticsDTO : public Model
{
public:
    virtual ~OpenAPIGoodsFeedbackStatisticsDTO() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Оценка товара. */
	int32 Rating = 0;
	/* Количество комментариев к отзыву.  Учитываются только ответы на отзывы, а не дочерние комментарии.  */
	int64 CommentsCount = 0;
	/* Рекомендуют ли этот товар. */
	TOptional<bool> Recommended;
	/* Количество баллов Плюса, которое автор получил за отзыв. */
	TOptional<int64> PaidAmount;
};

}
