# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WarehouseAddressDTO")

model_instance <- WarehouseAddressDTO$new()

test_that("city", {
  # tests for the property `city` (character)
  # Город.

  # uncomment below to test the property
  #expect_equal(model.instance$`city`, "EXPECTED_RESULT")
})

test_that("street", {
  # tests for the property `street` (character)
  # Улица.

  # uncomment below to test the property
  #expect_equal(model.instance$`street`, "EXPECTED_RESULT")
})

test_that("number", {
  # tests for the property `number` (character)
  # Номер дома.

  # uncomment below to test the property
  #expect_equal(model.instance$`number`, "EXPECTED_RESULT")
})

test_that("building", {
  # tests for the property `building` (character)
  # Номер строения.

  # uncomment below to test the property
  #expect_equal(model.instance$`building`, "EXPECTED_RESULT")
})

test_that("block", {
  # tests for the property `block` (character)
  # Номер корпуса.

  # uncomment below to test the property
  #expect_equal(model.instance$`block`, "EXPECTED_RESULT")
})

test_that("gps", {
  # tests for the property `gps` (GpsDTO)

  # uncomment below to test the property
  #expect_equal(model.instance$`gps`, "EXPECTED_RESULT")
})
