/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ympa_csharp_client.Model;
using ympa_csharp_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ympa_csharp_client.Test.Model
{
    /// <summary>
    ///  Class for testing BaseOfferDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BaseOfferDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BaseOfferDTO
        //private BaseOfferDTO instance;

        public BaseOfferDTOTests()
        {
            // TODO uncomment below to create an instance of BaseOfferDTO
            //instance = new BaseOfferDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BaseOfferDTO
        /// </summary>
        [Fact]
        public void BaseOfferDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" BaseOfferDTO
            //Assert.IsType<BaseOfferDTO>(instance);
        }

        /// <summary>
        /// Test the property 'OfferId'
        /// </summary>
        [Fact]
        public void OfferIdTest()
        {
            // TODO unit test for the property 'OfferId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'MarketCategoryId'
        /// </summary>
        [Fact]
        public void MarketCategoryIdTest()
        {
            // TODO unit test for the property 'MarketCategoryId'
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'Pictures'
        /// </summary>
        [Fact]
        public void PicturesTest()
        {
            // TODO unit test for the property 'Pictures'
        }

        /// <summary>
        /// Test the property 'Videos'
        /// </summary>
        [Fact]
        public void VideosTest()
        {
            // TODO unit test for the property 'Videos'
        }

        /// <summary>
        /// Test the property 'Manuals'
        /// </summary>
        [Fact]
        public void ManualsTest()
        {
            // TODO unit test for the property 'Manuals'
        }

        /// <summary>
        /// Test the property 'Vendor'
        /// </summary>
        [Fact]
        public void VendorTest()
        {
            // TODO unit test for the property 'Vendor'
        }

        /// <summary>
        /// Test the property 'Barcodes'
        /// </summary>
        [Fact]
        public void BarcodesTest()
        {
            // TODO unit test for the property 'Barcodes'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ManufacturerCountries'
        /// </summary>
        [Fact]
        public void ManufacturerCountriesTest()
        {
            // TODO unit test for the property 'ManufacturerCountries'
        }

        /// <summary>
        /// Test the property 'WeightDimensions'
        /// </summary>
        [Fact]
        public void WeightDimensionsTest()
        {
            // TODO unit test for the property 'WeightDimensions'
        }

        /// <summary>
        /// Test the property 'VendorCode'
        /// </summary>
        [Fact]
        public void VendorCodeTest()
        {
            // TODO unit test for the property 'VendorCode'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'ShelfLife'
        /// </summary>
        [Fact]
        public void ShelfLifeTest()
        {
            // TODO unit test for the property 'ShelfLife'
        }

        /// <summary>
        /// Test the property 'LifeTime'
        /// </summary>
        [Fact]
        public void LifeTimeTest()
        {
            // TODO unit test for the property 'LifeTime'
        }

        /// <summary>
        /// Test the property 'GuaranteePeriod'
        /// </summary>
        [Fact]
        public void GuaranteePeriodTest()
        {
            // TODO unit test for the property 'GuaranteePeriod'
        }

        /// <summary>
        /// Test the property 'CustomsCommodityCode'
        /// </summary>
        [Fact]
        public void CustomsCommodityCodeTest()
        {
            // TODO unit test for the property 'CustomsCommodityCode'
        }

        /// <summary>
        /// Test the property 'Certificates'
        /// </summary>
        [Fact]
        public void CertificatesTest()
        {
            // TODO unit test for the property 'Certificates'
        }

        /// <summary>
        /// Test the property 'BoxCount'
        /// </summary>
        [Fact]
        public void BoxCountTest()
        {
            // TODO unit test for the property 'BoxCount'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Downloadable'
        /// </summary>
        [Fact]
        public void DownloadableTest()
        {
            // TODO unit test for the property 'Downloadable'
        }

        /// <summary>
        /// Test the property 'Adult'
        /// </summary>
        [Fact]
        public void AdultTest()
        {
            // TODO unit test for the property 'Adult'
        }

        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Fact]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
    }
}
