/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ympa_csharp_client.Model;
using ympa_csharp_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ympa_csharp_client.Test.Model
{
    /// <summary>
    ///  Class for testing FeedContentDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeedContentDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeedContentDTO
        //private FeedContentDTO instance;

        public FeedContentDTOTests()
        {
            // TODO uncomment below to create an instance of FeedContentDTO
            //instance = new FeedContentDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeedContentDTO
        /// </summary>
        [Fact]
        public void FeedContentDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeedContentDTO
            //Assert.IsType<FeedContentDTO>(instance);
        }

        /// <summary>
        /// Test the property 'RejectedOffersCount'
        /// </summary>
        [Fact]
        public void RejectedOffersCountTest()
        {
            // TODO unit test for the property 'RejectedOffersCount'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'TotalOffersCount'
        /// </summary>
        [Fact]
        public void TotalOffersCountTest()
        {
            // TODO unit test for the property 'TotalOffersCount'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
