/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ympa_csharp_client.Model;
using ympa_csharp_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ympa_csharp_client.Test.Model
{
    /// <summary>
    ///  Class for testing GetPromoDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPromoDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPromoDTO
        //private GetPromoDTO instance;

        public GetPromoDTOTests()
        {
            // TODO uncomment below to create an instance of GetPromoDTO
            //instance = new GetPromoDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPromoDTO
        /// </summary>
        [Fact]
        public void GetPromoDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPromoDTO
            //Assert.IsType<GetPromoDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

        /// <summary>
        /// Test the property 'Participating'
        /// </summary>
        [Fact]
        public void ParticipatingTest()
        {
            // TODO unit test for the property 'Participating'
        }

        /// <summary>
        /// Test the property 'AssortmentInfo'
        /// </summary>
        [Fact]
        public void AssortmentInfoTest()
        {
            // TODO unit test for the property 'AssortmentInfo'
        }

        /// <summary>
        /// Test the property 'MechanicsInfo'
        /// </summary>
        [Fact]
        public void MechanicsInfoTest()
        {
            // TODO unit test for the property 'MechanicsInfo'
        }

        /// <summary>
        /// Test the property 'BestsellerInfo'
        /// </summary>
        [Fact]
        public void BestsellerInfoTest()
        {
            // TODO unit test for the property 'BestsellerInfo'
        }

        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Fact]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }
    }
}
