/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ympa_csharp_client.Model;
using ympa_csharp_client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ympa_csharp_client.Test.Model
{
    /// <summary>
    ///  Class for testing OrderTrackDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderTrackDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderTrackDTO
        //private OrderTrackDTO instance;

        public OrderTrackDTOTests()
        {
            // TODO uncomment below to create an instance of OrderTrackDTO
            //instance = new OrderTrackDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderTrackDTO
        /// </summary>
        [Fact]
        public void OrderTrackDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderTrackDTO
            //Assert.IsType<OrderTrackDTO>(instance);
        }

        /// <summary>
        /// Test the property 'TrackCode'
        /// </summary>
        [Fact]
        public void TrackCodeTest()
        {
            // TODO unit test for the property 'TrackCode'
        }

        /// <summary>
        /// Test the property 'DeliveryServiceId'
        /// </summary>
        [Fact]
        public void DeliveryServiceIdTest()
        {
            // TODO unit test for the property 'DeliveryServiceId'
        }
    }
}
