/*
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FieldStateType;
import org.openapitools.client.model.PriceCompetitivenessType;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetOfferRecommendationsRequest
 */
public class GetOfferRecommendationsRequestTest {
    private final GetOfferRecommendationsRequest model = new GetOfferRecommendationsRequest();

    /**
     * Model tests for GetOfferRecommendationsRequest
     */
    @Test
    public void testGetOfferRecommendationsRequest() {
        // TODO: test GetOfferRecommendationsRequest
    }

    /**
     * Test the property 'offerIds'
     */
    @Test
    public void offerIdsTest() {
        // TODO: test offerIds
    }

    /**
     * Test the property 'cofinancePriceFilter'
     */
    @Test
    public void cofinancePriceFilterTest() {
        // TODO: test cofinancePriceFilter
    }

    /**
     * Test the property 'recommendedCofinancePriceFilter'
     */
    @Test
    public void recommendedCofinancePriceFilterTest() {
        // TODO: test recommendedCofinancePriceFilter
    }

    /**
     * Test the property 'competitivenessFilter'
     */
    @Test
    public void competitivenessFilterTest() {
        // TODO: test competitivenessFilter
    }

}
