/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGetHiddenOffersResultDTO.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIGetHiddenOffersResultDTO::OAIGetHiddenOffersResultDTO(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIGetHiddenOffersResultDTO::OAIGetHiddenOffersResultDTO() {
    this->initializeModel();
}

OAIGetHiddenOffersResultDTO::~OAIGetHiddenOffersResultDTO() {}

void OAIGetHiddenOffersResultDTO::initializeModel() {

    m_paging_isSet = false;
    m_paging_isValid = false;

    m_hidden_offers_isSet = false;
    m_hidden_offers_isValid = false;
}

void OAIGetHiddenOffersResultDTO::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGetHiddenOffersResultDTO::fromJsonObject(QJsonObject json) {

    m_paging_isValid = ::OpenAPI::fromJsonValue(paging, json[QString("paging")]);
    m_paging_isSet = !json[QString("paging")].isNull() && m_paging_isValid;

    m_hidden_offers_isValid = ::OpenAPI::fromJsonValue(hidden_offers, json[QString("hiddenOffers")]);
    m_hidden_offers_isSet = !json[QString("hiddenOffers")].isNull() && m_hidden_offers_isValid;
}

QString OAIGetHiddenOffersResultDTO::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGetHiddenOffersResultDTO::asJsonObject() const {
    QJsonObject obj;
    if (paging.isSet()) {
        obj.insert(QString("paging"), ::OpenAPI::toJsonValue(paging));
    }
    if (hidden_offers.size() > 0) {
        obj.insert(QString("hiddenOffers"), ::OpenAPI::toJsonValue(hidden_offers));
    }
    return obj;
}

OAIScrollingPagerDTO OAIGetHiddenOffersResultDTO::getPaging() const {
    return paging;
}
void OAIGetHiddenOffersResultDTO::setPaging(const OAIScrollingPagerDTO &paging) {
    this->paging = paging;
    this->m_paging_isSet = true;
}

bool OAIGetHiddenOffersResultDTO::is_paging_Set() const{
    return m_paging_isSet;
}

bool OAIGetHiddenOffersResultDTO::is_paging_Valid() const{
    return m_paging_isValid;
}

QList<OAIHiddenOfferDTO> OAIGetHiddenOffersResultDTO::getHiddenOffers() const {
    return hidden_offers;
}
void OAIGetHiddenOffersResultDTO::setHiddenOffers(const QList<OAIHiddenOfferDTO> &hidden_offers) {
    this->hidden_offers = hidden_offers;
    this->m_hidden_offers_isSet = true;
}

bool OAIGetHiddenOffersResultDTO::is_hidden_offers_Set() const{
    return m_hidden_offers_isSet;
}

bool OAIGetHiddenOffersResultDTO::is_hidden_offers_Valid() const{
    return m_hidden_offers_isValid;
}

bool OAIGetHiddenOffersResultDTO::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (paging.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (hidden_offers.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGetHiddenOffersResultDTO::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_hidden_offers_isValid && true;
}

} // namespace OpenAPI
