/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIOrderUpdateStatusType.h
 *
 * Изменился ли статус заказа:  * &#x60;OK&#x60; — статус изменен.  * &#x60;ERROR&#x60; — статус не изменен. В этом случае появится сообщение об ошибке в параметре &#x60;errorDetails&#x60;. 
 */

#ifndef OAIOrderUpdateStatusType_H
#define OAIOrderUpdateStatusType_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIOrderUpdateStatusType : public OAIEnum {
public:
    OAIOrderUpdateStatusType();
    OAIOrderUpdateStatusType(QString json);
    ~OAIOrderUpdateStatusType() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIOrderUpdateStatusType {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        OK, 
        ERROR
    };
    OAIOrderUpdateStatusType::eOAIOrderUpdateStatusType getValue() const;
    void setValue(const OAIOrderUpdateStatusType::eOAIOrderUpdateStatusType& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIOrderUpdateStatusType m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIOrderUpdateStatusType)

#endif // OAIOrderUpdateStatusType_H
