package org.openapitools.model;

import groovy.transform.Canonical
import io.swagger.annotations.ApiModel;

enum TariffType {

    AGENCY_COMMISSION("AGENCY_COMMISSION"),
    
    PAYMENT_TRANSFER("PAYMENT_TRANSFER"),
    
    STORAGE("STORAGE"),
    
    WITHDRAW("WITHDRAW"),
    
    SURPLUS("SURPLUS"),
    
    FEE("FEE"),
    
    DELIVERY_TO_CUSTOMER("DELIVERY_TO_CUSTOMER"),
    
    CROSSREGIONAL_DELIVERY("CROSSREGIONAL_DELIVERY"),
    
    CROSSREGIONAL_DELIVERY_RETURN("CROSSREGIONAL_DELIVERY_RETURN"),
    
    DISPOSAL("DISPOSAL"),
    
    SORTING_CENTER_STORAGE("SORTING_CENTER_STORAGE"),
    
    EXPRESS_DELIVERY("EXPRESS_DELIVERY"),
    
    FF_XDOC_SUPPLY_BOX("FF_XDOC_SUPPLY_BOX"),
    
    FF_XDOC_SUPPLY_PALLET("FF_XDOC_SUPPLY_PALLET"),
    
    SORTING("SORTING"),
    
    MIDDLE_MILE("MIDDLE_MILE"),
    
    RETURN_PROCESSING("RETURN_PROCESSING"),
    
    EXPRESS_CANCELLED_BY_PARTNER("EXPRESS_CANCELLED_BY_PARTNER"),
    
    DELIVERY_TO_CUSTOMER_RETURN("DELIVERY_TO_CUSTOMER_RETURN"),
    
    CROSSBORDER_DELIVERY("CROSSBORDER_DELIVERY"),
    
    INTAKE_SORTING_BULKY_CARGO("INTAKE_SORTING_BULKY_CARGO"),
    
    INTAKE_SORTING_SMALL_GOODS("INTAKE_SORTING_SMALL_GOODS"),
    
    INTAKE_SORTING_DAILY("INTAKE_SORTING_DAILY"),
    
    FF_STORAGE_BILLING("FF_STORAGE_BILLING"),
    
    CANCELLED_ORDER_FEE_QI("CANCELLED_ORDER_FEE_QI"),
    
    LATE_ORDER_EXECUTION_FEE_QI("LATE_ORDER_EXECUTION_FEE_QI")

    private final String value

    TariffType(String value) {
        this.value = value
    }

    String getValue() {
        value
    }

    @Override
    String toString() {
        String.valueOf(value)
    }
}
