<?php

/**
 * Партнерский API Маркета
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 * The version of the OpenAPI document: LATEST
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * OrderStatusType
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class OrderStatusType extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "string",
  "description" : "Статус заказа:\n\n* `CANCELLED` — отменен.\n\n* `DELIVERED` — получен покупателем.\n\n* `DELIVERY` — передан в службу доставки.\n\n* `PICKUP` — доставлен в пункт самовывоза.\n\n* `PROCESSING` — находится в обработке.\n\n* `PENDING` — ожидает обработки со стороны продавца.\n\n* `UNPAID` — оформлен, но еще не оплачен (если выбрана оплата при оформлении).\n\n* `PLACING` — оформляется, подготовка к резервированию.\n\n* `RESERVED` — зарезервирован, но недооформлен.\n\n* `PARTIALLY_RETURNED` — возвращен частично.\n\n* `RETURNED` — возвращен полностью.\n\n* `UNKNOWN` — неизвестный статус.\n\nТакже могут возвращаться другие значения. Обрабатывать их не требуется.\n",
  "enum" : [ "PLACING", "RESERVED", "UNPAID", "PROCESSING", "DELIVERY", "PICKUP", "DELIVERED", "CANCELLED", "PENDING", "PARTIALLY_RETURNED", "RETURNED", "UNKNOWN" ]
}
SCHEMA;
}
