(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_bids_info_for_business : business_id:int64 -> ?page_token:string -> ?limit:int32 -> get_bids_info_request_t:Get_bids_info_request.t -> unit -> Get_bids_info_response.t Lwt.t
val get_bids_recommendations : business_id:int64 -> get_bids_recommendations_request_t:Get_bids_recommendations_request.t -> Get_bids_recommendations_response.t Lwt.t
val put_bids_for_business : business_id:int64 -> put_sku_bids_request_t:Put_sku_bids_request.t -> Empty_api_response.t Lwt.t
val put_bids_for_campaign : campaign_id:int64 -> put_sku_bids_request_t:Put_sku_bids_request.t -> Empty_api_response.t Lwt.t
