// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * API version: LATEST
 */

package ympa_go_server




// OrderStatusChangeDeliveryDto - Информация о доставке.
type OrderStatusChangeDeliveryDto struct {

	Dates OrderStatusChangeDeliveryDatesDto `json:"dates,omitempty"`
}

// AssertOrderStatusChangeDeliveryDtoRequired checks if the required fields are not zero-ed
func AssertOrderStatusChangeDeliveryDtoRequired(obj OrderStatusChangeDeliveryDto) error {
	if err := AssertOrderStatusChangeDeliveryDatesDtoRequired(obj.Dates); err != nil {
		return err
	}
	return nil
}

// AssertOrderStatusChangeDeliveryDtoConstraints checks if the values respects the defined constraints
func AssertOrderStatusChangeDeliveryDtoConstraints(obj OrderStatusChangeDeliveryDto) error {
	if err := AssertOrderStatusChangeDeliveryDatesDtoConstraints(obj.Dates); err != nil {
		return err
	}
	return nil
}
