// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * API version: LATEST
 */

package ympa_go_server




type GetCategoriesResponse struct {

	Status ApiResponseStatusType `json:"status,omitempty"`

	Result CategoryDto `json:"result,omitempty"`
}

// AssertGetCategoriesResponseRequired checks if the required fields are not zero-ed
func AssertGetCategoriesResponseRequired(obj GetCategoriesResponse) error {
	if err := AssertCategoryDtoRequired(obj.Result); err != nil {
		return err
	}
	return nil
}

// AssertGetCategoriesResponseConstraints checks if the values respects the defined constraints
func AssertGetCategoriesResponseConstraints(obj GetCategoriesResponse) error {
	if err := AssertCategoryDtoConstraints(obj.Result); err != nil {
		return err
	}
	return nil
}
