// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * API version: LATEST
 */

package ympa_go_server




// UpdateOrderItemRequest - Запрос на обновление состава заказа.
type UpdateOrderItemRequest struct {

	// Список товаров в заказе.  Если магазин не передал информацию о товаре во входных данных, он будет удален из заказа.  Обязательный параметр. 
	Items []OrderItemModificationDto `json:"items"`

	Reason OrderItemsModificationRequestReasonType `json:"reason,omitempty"`
}

// AssertUpdateOrderItemRequestRequired checks if the required fields are not zero-ed
func AssertUpdateOrderItemRequestRequired(obj UpdateOrderItemRequest) error {
	elements := map[string]interface{}{
		"items": obj.Items,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Items {
		if err := AssertOrderItemModificationDtoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertUpdateOrderItemRequestConstraints checks if the values respects the defined constraints
func AssertUpdateOrderItemRequestConstraints(obj UpdateOrderItemRequest) error {
	for _, el := range obj.Items {
		if err := AssertOrderItemModificationDtoConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
