/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * API version: LATEST
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ympa_go_gin_server

// EnrichedModelDto - Модель товара.
type EnrichedModelDto struct {

	// Идентификатор модели товара.
	Id int64 `json:"id,omitempty"`

	// Название модели товара.
	Name string `json:"name,omitempty"`

	Prices ModelPriceDto `json:"prices,omitempty"`

	// Список первых десяти предложений, расположенных на карточке модели.  В ответе на запрос возвращаются предложения различных магазинов. Если есть несколько предложений от одного магазина, в ответе отображается только одно, наиболее релевантное из них. 
	Offers *[]ModelOfferDto `json:"offers,omitempty"`

	// Суммарное количество предложений в розничных магазинах в регионе. Учитываются все предложения от каждого магазина.
	OfflineOffers int32 `json:"offlineOffers,omitempty"`

	// Суммарное количество предложений в интернет-магазинах в регионе. Учитываются все предложения от каждого магазина.
	OnlineOffers int32 `json:"onlineOffers,omitempty"`
}
