#
# Партнерский API Маркета
# API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
# Version: LATEST
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ympa_powershell_client' -name 'UpdatePromoOfferDTO' {
    Context 'UpdatePromoOfferDTO' {
        It 'Initialize-UpdatePromoOfferDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-UpdatePromoOfferDTO -OfferId "TEST_VALUE" -Params "TEST_VALUE"
            #$NewObject | Should -BeOfType UpdatePromoOfferDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
