/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PalletsCountDTO.h
 *
 * Количество палет в отгрузке.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PalletsCountDTO_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PalletsCountDTO_H_


#include "ympa_cpp_restsdk_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Количество палет в отгрузке.
/// </summary>
class  PalletsCountDTO
    : public ModelBase
{
public:
    PalletsCountDTO();
    virtual ~PalletsCountDTO();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PalletsCountDTO members

    /// <summary>
    /// Количество палет, которое заявил продавец.
    /// </summary>
    int32_t getPlanned() const;
    bool plannedIsSet() const;
    void unsetPlanned();

    void setPlanned(int32_t value);

    /// <summary>
    /// Количество палет, которое приняли в сортировочном центре.
    /// </summary>
    int32_t getFact() const;
    bool factIsSet() const;
    void unsetFact();

    void setFact(int32_t value);


protected:
    int32_t m_Planned;
    bool m_PlannedIsSet;
    int32_t m_Fact;
    bool m_FactIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PalletsCountDTO_H_ */
