/**
* Партнерский API Маркета
* API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
*
* The version of the OpenAPI document: LATEST
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ympa_kotlin_vertx_server.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * Информация о категории.  Категория считается листовой, если у нее нет дочерних категорий. 
 * @param id Идентификатор категории.
 * @param name Название категории.
 * @param children Дочерние категории.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class CategoryDTO (
    /* Идентификатор категории. */
    @SerializedName("id") private val _id: kotlin.Long?,
    /* Название категории. */
    @SerializedName("name") private val _name: kotlin.String?,
    /* Дочерние категории. */
    val children: kotlin.Array<CategoryDTO>? = null
) {

        val id get() = _id ?: throw IllegalArgumentException("id is required")
                    
        val name get() = _name ?: throw IllegalArgumentException("name is required")
                    
}

