# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ympa_python_aiohttp_server.models.base_model import Model
from ympa_python_aiohttp_server import util


class GoodsStatsWeightDimensionsDTO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, length: float=None, width: float=None, height: float=None, weight: float=None):
        """GoodsStatsWeightDimensionsDTO - a model defined in OpenAPI

        :param length: The length of this GoodsStatsWeightDimensionsDTO.
        :param width: The width of this GoodsStatsWeightDimensionsDTO.
        :param height: The height of this GoodsStatsWeightDimensionsDTO.
        :param weight: The weight of this GoodsStatsWeightDimensionsDTO.
        """
        self.openapi_types = {
            'length': float,
            'width': float,
            'height': float,
            'weight': float
        }

        self.attribute_map = {
            'length': 'length',
            'width': 'width',
            'height': 'height',
            'weight': 'weight'
        }

        self._length = length
        self._width = width
        self._height = height
        self._weight = weight

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GoodsStatsWeightDimensionsDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GoodsStatsWeightDimensionsDTO of this GoodsStatsWeightDimensionsDTO.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def length(self):
        """Gets the length of this GoodsStatsWeightDimensionsDTO.

        Длина товара в сантиметрах.

        :return: The length of this GoodsStatsWeightDimensionsDTO.
        :rtype: float
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this GoodsStatsWeightDimensionsDTO.

        Длина товара в сантиметрах.

        :param length: The length of this GoodsStatsWeightDimensionsDTO.
        :type length: float
        """

        self._length = length

    @property
    def width(self):
        """Gets the width of this GoodsStatsWeightDimensionsDTO.

        Ширина товара в сантиметрах.

        :return: The width of this GoodsStatsWeightDimensionsDTO.
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this GoodsStatsWeightDimensionsDTO.

        Ширина товара в сантиметрах.

        :param width: The width of this GoodsStatsWeightDimensionsDTO.
        :type width: float
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this GoodsStatsWeightDimensionsDTO.

        Высота товара в сантиметрах.

        :return: The height of this GoodsStatsWeightDimensionsDTO.
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this GoodsStatsWeightDimensionsDTO.

        Высота товара в сантиметрах.

        :param height: The height of this GoodsStatsWeightDimensionsDTO.
        :type height: float
        """

        self._height = height

    @property
    def weight(self):
        """Gets the weight of this GoodsStatsWeightDimensionsDTO.

        Вес товара в килограммах.

        :return: The weight of this GoodsStatsWeightDimensionsDTO.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this GoodsStatsWeightDimensionsDTO.

        Вес товара в килограммах.

        :param weight: The weight of this GoodsStatsWeightDimensionsDTO.
        :type weight: float
        """

        self._weight = weight
