dependencies:
  factories:
    Mezzio\Router\RouterInterface: Articus\PathHandler\RouteInjectionFactory
    Articus\PathHandler\MetadataProviderInterface: Articus\PathHandler\MetadataProvider\Factory\Annotation
    Articus\PathHandler\Handler\PluginManager: Articus\PathHandler\Handler\Factory\PluginManager
    Articus\PathHandler\Consumer\PluginManager: Articus\PathHandler\Consumer\Factory\PluginManager
    Articus\PathHandler\Attribute\PluginManager: Articus\PathHandler\Attribute\Factory\PluginManager
    Articus\PathHandler\Producer\PluginManager: Articus\PathHandler\Producer\Factory\PluginManager

Articus\PathHandler\RouteInjectionFactory:
  paths:
    '':
    - App\Handler\BusinessesBusinessIdBids
    - App\Handler\BusinessesBusinessIdBidsInfo
    - App\Handler\BusinessesBusinessIdBidsRecommendations
    - App\Handler\BusinessesBusinessIdChats
    - App\Handler\BusinessesBusinessIdChatsFileSend
    - App\Handler\BusinessesBusinessIdChatsHistory
    - App\Handler\BusinessesBusinessIdChatsMessage
    - App\Handler\BusinessesBusinessIdChatsNew
    - App\Handler\BusinessesBusinessIdGoodsFeedback
    - App\Handler\BusinessesBusinessIdGoodsFeedbackComments
    - App\Handler\BusinessesBusinessIdGoodsFeedbackCommentsDelete
    - App\Handler\BusinessesBusinessIdGoodsFeedbackCommentsUpdate
    - App\Handler\BusinessesBusinessIdGoodsFeedbackSkipReaction
    - App\Handler\BusinessesBusinessIdOfferCards
    - App\Handler\BusinessesBusinessIdOfferCardsUpdate
    - App\Handler\BusinessesBusinessIdOfferMappings
    - App\Handler\BusinessesBusinessIdOfferMappingsArchive
    - App\Handler\BusinessesBusinessIdOfferMappingsDelete
    - App\Handler\BusinessesBusinessIdOfferMappingsSuggestions
    - App\Handler\BusinessesBusinessIdOfferMappingsUnarchive
    - App\Handler\BusinessesBusinessIdOfferMappingsUpdate
    - App\Handler\BusinessesBusinessIdOfferPricesUpdates
    - App\Handler\BusinessesBusinessIdOffersRecommendations
    - App\Handler\BusinessesBusinessIdPriceQuarantine
    - App\Handler\BusinessesBusinessIdPriceQuarantineConfirm
    - App\Handler\BusinessesBusinessIdPromos
    - App\Handler\BusinessesBusinessIdPromosOffers
    - App\Handler\BusinessesBusinessIdPromosOffersDelete
    - App\Handler\BusinessesBusinessIdPromosOffersUpdate
    - App\Handler\BusinessesBusinessIdRatingsQuality
    - App\Handler\BusinessesBusinessIdSettings
    - App\Handler\BusinessesBusinessIdWarehouses
    - App\Handler\Campaigns
    - App\Handler\CampaignsByLoginLogin
    - App\Handler\CampaignsCampaignId
    - App\Handler\CampaignsCampaignIdBids
    - App\Handler\CampaignsCampaignIdFeedbackUpdates
    - App\Handler\CampaignsCampaignIdFeeds
    - App\Handler\CampaignsCampaignIdFeedsFeedId
    - App\Handler\CampaignsCampaignIdFeedsFeedIdIndexLogs
    - App\Handler\CampaignsCampaignIdFeedsFeedIdParams
    - App\Handler\CampaignsCampaignIdFeedsFeedIdRefresh
    - App\Handler\CampaignsCampaignIdFirstMileShipments
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentId
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdAct
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdConfirm
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdDiscrepancyAct
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdInboundAct
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdOrdersInfo
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdOrdersTransfer
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdPalletLabels
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdPallets
    - App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdTransportationWaybill
    - App\Handler\CampaignsCampaignIdHiddenOffers
    - App\Handler\CampaignsCampaignIdHiddenOffersDelete
    - App\Handler\CampaignsCampaignIdLogins
    - App\Handler\CampaignsCampaignIdOfferMappingEntries
    - App\Handler\CampaignsCampaignIdOfferMappingEntriesSuggestions
    - App\Handler\CampaignsCampaignIdOfferMappingEntriesUpdates
    - App\Handler\CampaignsCampaignIdOfferPrices
    - App\Handler\CampaignsCampaignIdOfferPricesSuggestions
    - App\Handler\CampaignsCampaignIdOfferPricesUpdates
    - App\Handler\CampaignsCampaignIdOffers
    - App\Handler\CampaignsCampaignIdOffersAll
    - App\Handler\CampaignsCampaignIdOffersDelete
    - App\Handler\CampaignsCampaignIdOffersStocks
    - App\Handler\CampaignsCampaignIdOffersUpdate
    - App\Handler\CampaignsCampaignIdOrders
    - App\Handler\CampaignsCampaignIdOrdersStatusUpdate
    - App\Handler\CampaignsCampaignIdOrdersOrderId
    - App\Handler\CampaignsCampaignIdOrdersOrderIdBoxes
    - App\Handler\CampaignsCampaignIdOrdersOrderIdBusinessBuyer
    - App\Handler\CampaignsCampaignIdOrdersOrderIdBuyer
    - App\Handler\CampaignsCampaignIdOrdersOrderIdCancellationAccept
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliverDigitalGoods
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryDate
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryLabels
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryLabelsData
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryShipmentsShipmentIdBoxes
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryShipmentsShipmentIdBoxesBoxIdLabel
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryStorageLimit
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryTrack
    - App\Handler\CampaignsCampaignIdOrdersOrderIdDocuments
    - App\Handler\CampaignsCampaignIdOrdersOrderIdIdentifiers
    - App\Handler\CampaignsCampaignIdOrdersOrderIdItems
    - App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnId
    - App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdApplication
    - App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdDecision
    - App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdDecisionSubmit
    - App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdDecisionItemIdImageImageHash
    - App\Handler\CampaignsCampaignIdOrdersOrderIdStatus
    - App\Handler\CampaignsCampaignIdOrdersOrderIdVerifyEac
    - App\Handler\CampaignsCampaignIdOutlets
    - App\Handler\CampaignsCampaignIdOutletsLicenses
    - App\Handler\CampaignsCampaignIdOutletsOutletId
    - App\Handler\CampaignsCampaignIdPriceQuarantine
    - App\Handler\CampaignsCampaignIdPriceQuarantineConfirm
    - App\Handler\CampaignsCampaignIdRatingsQualityDetails
    - App\Handler\CampaignsCampaignIdRegion
    - App\Handler\CampaignsCampaignIdReturns
    - App\Handler\CampaignsCampaignIdSettings
    - App\Handler\CampaignsCampaignIdShipmentsReceptionTransferAct
    - App\Handler\CampaignsCampaignIdStatsOrders
    - App\Handler\CampaignsCampaignIdStatsSkus
    - App\Handler\CategoriesMaxSaleQuantum
    - App\Handler\CategoriesTree
    - App\Handler\CategoryCategoryIdParameters
    - App\Handler\DeliveryServices
    - App\Handler\Models
    - App\Handler\ModelsOffers
    - App\Handler\ModelsModelId
    - App\Handler\ModelsModelIdOffers
    - App\Handler\Regions
    - App\Handler\RegionsRegionId
    - App\Handler\RegionsRegionIdChildren
    - App\Handler\ReportsBoostConsolidatedGenerate
    - App\Handler\ReportsCompetitorsPositionGenerate
    - App\Handler\ReportsDocumentsLabelsGenerate
    - App\Handler\ReportsDocumentsShipmentListGenerate
    - App\Handler\ReportsGoodsFeedbackGenerate
    - App\Handler\ReportsGoodsMovementGenerate
    - App\Handler\ReportsGoodsRealizationGenerate
    - App\Handler\ReportsGoodsTurnoverGenerate
    - App\Handler\ReportsInfoReportId
    - App\Handler\ReportsPricesGenerate
    - App\Handler\ReportsShelfStatisticsGenerate
    - App\Handler\ReportsShowsSalesGenerate
    - App\Handler\ReportsStocksOnWarehousesGenerate
    - App\Handler\ReportsUnitedMarketplaceServicesGenerate
    - App\Handler\ReportsUnitedNettingGenerate
    - App\Handler\ReportsUnitedOrdersGenerate
    - App\Handler\TariffsCalculate
    - App\Handler\Warehouses

Articus\PathHandler\Handler\PluginManager:
  abstract_factories:
  - Laminas\ServiceManager\AbstractFactory\ConfigAbstractFactory

#Articus\PathHandler\Consumer\PluginManager:
#  factories:
#  invokables:

#Articus\PathHandler\Attribute\PluginManager:
#  factories:
#  invokables:

#Articus\PathHandler\Producer\PluginManager:
#  factories:
#  invokables:

Laminas\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\BusinessesBusinessIdBids: []
  App\Handler\BusinessesBusinessIdBidsInfo: []
  App\Handler\BusinessesBusinessIdBidsRecommendations: []
  App\Handler\BusinessesBusinessIdChats: []
  App\Handler\BusinessesBusinessIdChatsFileSend: []
  App\Handler\BusinessesBusinessIdChatsHistory: []
  App\Handler\BusinessesBusinessIdChatsMessage: []
  App\Handler\BusinessesBusinessIdChatsNew: []
  App\Handler\BusinessesBusinessIdGoodsFeedback: []
  App\Handler\BusinessesBusinessIdGoodsFeedbackComments: []
  App\Handler\BusinessesBusinessIdGoodsFeedbackCommentsDelete: []
  App\Handler\BusinessesBusinessIdGoodsFeedbackCommentsUpdate: []
  App\Handler\BusinessesBusinessIdGoodsFeedbackSkipReaction: []
  App\Handler\BusinessesBusinessIdOfferCards: []
  App\Handler\BusinessesBusinessIdOfferCardsUpdate: []
  App\Handler\BusinessesBusinessIdOfferMappings: []
  App\Handler\BusinessesBusinessIdOfferMappingsArchive: []
  App\Handler\BusinessesBusinessIdOfferMappingsDelete: []
  App\Handler\BusinessesBusinessIdOfferMappingsSuggestions: []
  App\Handler\BusinessesBusinessIdOfferMappingsUnarchive: []
  App\Handler\BusinessesBusinessIdOfferMappingsUpdate: []
  App\Handler\BusinessesBusinessIdOfferPricesUpdates: []
  App\Handler\BusinessesBusinessIdOffersRecommendations: []
  App\Handler\BusinessesBusinessIdPriceQuarantine: []
  App\Handler\BusinessesBusinessIdPriceQuarantineConfirm: []
  App\Handler\BusinessesBusinessIdPromos: []
  App\Handler\BusinessesBusinessIdPromosOffers: []
  App\Handler\BusinessesBusinessIdPromosOffersDelete: []
  App\Handler\BusinessesBusinessIdPromosOffersUpdate: []
  App\Handler\BusinessesBusinessIdRatingsQuality: []
  App\Handler\BusinessesBusinessIdSettings: []
  App\Handler\BusinessesBusinessIdWarehouses: []
  App\Handler\Campaigns: []
  App\Handler\CampaignsByLoginLogin: []
  App\Handler\CampaignsCampaignId: []
  App\Handler\CampaignsCampaignIdBids: []
  App\Handler\CampaignsCampaignIdFeedbackUpdates: []
  App\Handler\CampaignsCampaignIdFeeds: []
  App\Handler\CampaignsCampaignIdFeedsFeedId: []
  App\Handler\CampaignsCampaignIdFeedsFeedIdIndexLogs: []
  App\Handler\CampaignsCampaignIdFeedsFeedIdParams: []
  App\Handler\CampaignsCampaignIdFeedsFeedIdRefresh: []
  App\Handler\CampaignsCampaignIdFirstMileShipments: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentId: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdAct: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdConfirm: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdDiscrepancyAct: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdInboundAct: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdOrdersInfo: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdOrdersTransfer: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdPalletLabels: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdPallets: []
  App\Handler\CampaignsCampaignIdFirstMileShipmentsShipmentIdTransportationWaybill: []
  App\Handler\CampaignsCampaignIdHiddenOffers: []
  App\Handler\CampaignsCampaignIdHiddenOffersDelete: []
  App\Handler\CampaignsCampaignIdLogins: []
  App\Handler\CampaignsCampaignIdOfferMappingEntries: []
  App\Handler\CampaignsCampaignIdOfferMappingEntriesSuggestions: []
  App\Handler\CampaignsCampaignIdOfferMappingEntriesUpdates: []
  App\Handler\CampaignsCampaignIdOfferPrices: []
  App\Handler\CampaignsCampaignIdOfferPricesSuggestions: []
  App\Handler\CampaignsCampaignIdOfferPricesUpdates: []
  App\Handler\CampaignsCampaignIdOffers: []
  App\Handler\CampaignsCampaignIdOffersAll: []
  App\Handler\CampaignsCampaignIdOffersDelete: []
  App\Handler\CampaignsCampaignIdOffersStocks: []
  App\Handler\CampaignsCampaignIdOffersUpdate: []
  App\Handler\CampaignsCampaignIdOrders: []
  App\Handler\CampaignsCampaignIdOrdersStatusUpdate: []
  App\Handler\CampaignsCampaignIdOrdersOrderId: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdBoxes: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdBusinessBuyer: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdBuyer: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdCancellationAccept: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliverDigitalGoods: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryDate: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryLabels: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryLabelsData: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryShipmentsShipmentIdBoxes: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryShipmentsShipmentIdBoxesBoxIdLabel: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryStorageLimit: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDeliveryTrack: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdDocuments: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdIdentifiers: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdItems: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnId: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdApplication: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdDecision: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdDecisionSubmit: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdReturnsReturnIdDecisionItemIdImageImageHash: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdStatus: []
  App\Handler\CampaignsCampaignIdOrdersOrderIdVerifyEac: []
  App\Handler\CampaignsCampaignIdOutlets: []
  App\Handler\CampaignsCampaignIdOutletsLicenses: []
  App\Handler\CampaignsCampaignIdOutletsOutletId: []
  App\Handler\CampaignsCampaignIdPriceQuarantine: []
  App\Handler\CampaignsCampaignIdPriceQuarantineConfirm: []
  App\Handler\CampaignsCampaignIdRatingsQualityDetails: []
  App\Handler\CampaignsCampaignIdRegion: []
  App\Handler\CampaignsCampaignIdReturns: []
  App\Handler\CampaignsCampaignIdSettings: []
  App\Handler\CampaignsCampaignIdShipmentsReceptionTransferAct: []
  App\Handler\CampaignsCampaignIdStatsOrders: []
  App\Handler\CampaignsCampaignIdStatsSkus: []
  App\Handler\CategoriesMaxSaleQuantum: []
  App\Handler\CategoriesTree: []
  App\Handler\CategoryCategoryIdParameters: []
  App\Handler\DeliveryServices: []
  App\Handler\Models: []
  App\Handler\ModelsOffers: []
  App\Handler\ModelsModelId: []
  App\Handler\ModelsModelIdOffers: []
  App\Handler\Regions: []
  App\Handler\RegionsRegionId: []
  App\Handler\RegionsRegionIdChildren: []
  App\Handler\ReportsBoostConsolidatedGenerate: []
  App\Handler\ReportsCompetitorsPositionGenerate: []
  App\Handler\ReportsDocumentsLabelsGenerate: []
  App\Handler\ReportsDocumentsShipmentListGenerate: []
  App\Handler\ReportsGoodsFeedbackGenerate: []
  App\Handler\ReportsGoodsMovementGenerate: []
  App\Handler\ReportsGoodsRealizationGenerate: []
  App\Handler\ReportsGoodsTurnoverGenerate: []
  App\Handler\ReportsInfoReportId: []
  App\Handler\ReportsPricesGenerate: []
  App\Handler\ReportsShelfStatisticsGenerate: []
  App\Handler\ReportsShowsSalesGenerate: []
  App\Handler\ReportsStocksOnWarehousesGenerate: []
  App\Handler\ReportsUnitedMarketplaceServicesGenerate: []
  App\Handler\ReportsUnitedNettingGenerate: []
  App\Handler\ReportsUnitedOrdersGenerate: []
  App\Handler\TariffsCalculate: []
  App\Handler\Warehouses: []
