=begin
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

The version of the OpenAPI document: LATEST
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class GetPromoDTO < ApplicationRecord
  validates_presence_of :id
  validates_presence_of :name
  validates_presence_of :period
  validates_presence_of :participating
  validates_presence_of :assortment_info
  validates_presence_of :mechanics_info
  validates_presence_of :bestseller_info

  serialize :channels, Array
end
