namespace ympa_fsharp_functions_server.Model

open System
open System.Collections.Generic
open Newtonsoft.Json

module OrderPromoType =

  //#region OrderPromoType

  let DIRECTDISCOUNTEnum = "DIRECT_DISCOUNT"
  let BLUESETEnum = "BLUE_SET"
  let BLUEFLASHEnum = "BLUE_FLASH"
  let GENERICBUNDLEEnum = "GENERIC_BUNDLE"
  let MARKETCOUPONEnum = "MARKET_COUPON"
  let MARKETPROMOCODEEnum = "MARKET_PROMOCODE"
  let MARKETDEALEnum = "MARKET_DEAL"
  let MARKETBLUEEnum = "MARKET_BLUE"
  let MARKETPRIMEEnum = "MARKET_PRIME"
  let YANDEXPLUSEnum = "YANDEX_PLUS"
  let BERUPLUSEnum = "BERU_PLUS"
  let MARKETCOINEnum = "MARKET_COIN"
  let YANDEXEMPLOYEEEnum = "YANDEX_EMPLOYEE"
  let LIMITEDFREEDELIVERYPROMOEnum = "LIMITED_FREE_DELIVERY_PROMO"
  let FREEDELIVERYTHRESHOLDEnum = "FREE_DELIVERY_THRESHOLD"
  let MULTICARTDISCOUNTEnum = "MULTICART_DISCOUNT"
  let PRICEDROPASYOUSHOPEnum = "PRICE_DROP_AS_YOU_SHOP"
  let FREEDELIVERYFORLDIEnum = "FREE_DELIVERY_FOR_LDI"
  let FREEDELIVERYFORLSCEnum = "FREE_DELIVERY_FOR_LSC"
  let SECRETSALEEnum = "SECRET_SALE"
  let FREEPICKUPEnum = "FREE_PICKUP"
  let CHEAPESTASGIFTEnum = "CHEAPEST_AS_GIFT"
  let CASHBACKEnum = "CASHBACK"
  let SUPPLIERMULTICARTDISCOUNTEnum = "SUPPLIER_MULTICART_DISCOUNT"
  let SPREADDISCOUNTCOUNTEnum = "SPREAD_DISCOUNT_COUNT"
  let SPREADDISCOUNTRECEIPTEnum = "SPREAD_DISCOUNT_RECEIPT"
  let ANNOUNCEMENTPROMOEnum = "ANNOUNCEMENT_PROMO"
  let DISCOUNTBYPAYMENTTYPEEnum = "DISCOUNT_BY_PAYMENT_TYPE"
  let PERCENTDISCOUNTEnum = "PERCENT_DISCOUNT"
  let DCOEXTRADISCOUNTEnum = "DCO_EXTRA_DISCOUNT"
  let EMPTYPROMOEnum = "EMPTY_PROMO"
  let BLOCKINGPROMOEnum = "BLOCKING_PROMO"
  let UNKNOWNEnum = "UNKNOWN"
  type OrderPromoType = string

  //#endregion
