namespace ympa_fsharp_functions_server.Model

open System
open System.Collections.Generic
open Newtonsoft.Json

module RejectedPromoOfferUpdateReasonType =

  //#region RejectedPromoOfferUpdateReasonType

  let OFFERDOESNOTEXISTEnum = "OFFER_DOES_NOT_EXIST"
  let OFFERDUPLICATIONEnum = "OFFER_DUPLICATION"
  let OFFERNOTELIGIBLEFORPROMOEnum = "OFFER_NOT_ELIGIBLE_FOR_PROMO"
  let OFFERPROMOSMAXBYTESIZEEXCEEDEDEnum = "OFFER_PROMOS_MAX_BYTE_SIZE_EXCEEDED"
  let DEADLINEFORFOCUSPROMOSEXCEEDEDEnum = "DEADLINE_FOR_FOCUS_PROMOS_EXCEEDED"
  let EMPTYOLDPRICEEnum = "EMPTY_OLD_PRICE"
  let EMPTYPROMOPRICEEnum = "EMPTY_PROMO_PRICE"
  let MAXPROMOPRICEEXCEEDEDEnum = "MAX_PROMO_PRICE_EXCEEDED"
  let PROMOPRICEBIGGERTHANMAXEnum = "PROMO_PRICE_BIGGER_THAN_MAX"
  let PROMOPRICESMALLERTHANMINEnum = "PROMO_PRICE_SMALLER_THAN_MIN"
  type RejectedPromoOfferUpdateReasonType = string

  //#endregion
