namespace ympa_fsharp_functions_server.Model

open System
open System.Collections.Generic
open Newtonsoft.Json

module TariffType =

  //#region TariffType

  let AGENCYCOMMISSIONEnum = "AGENCY_COMMISSION"
  let PAYMENTTRANSFEREnum = "PAYMENT_TRANSFER"
  let STORAGEEnum = "STORAGE"
  let WITHDRAWEnum = "WITHDRAW"
  let SURPLUSEnum = "SURPLUS"
  let FEEEnum = "FEE"
  let DELIVERYTOCUSTOMEREnum = "DELIVERY_TO_CUSTOMER"
  let CROSSREGIONALDELIVERYEnum = "CROSSREGIONAL_DELIVERY"
  let CROSSREGIONALDELIVERYRETURNEnum = "CROSSREGIONAL_DELIVERY_RETURN"
  let DISPOSALEnum = "DISPOSAL"
  let SORTINGCENTERSTORAGEEnum = "SORTING_CENTER_STORAGE"
  let EXPRESSDELIVERYEnum = "EXPRESS_DELIVERY"
  let FFXDOCSUPPLYBOXEnum = "FF_XDOC_SUPPLY_BOX"
  let FFXDOCSUPPLYPALLETEnum = "FF_XDOC_SUPPLY_PALLET"
  let SORTINGEnum = "SORTING"
  let MIDDLEMILEEnum = "MIDDLE_MILE"
  let RETURNPROCESSINGEnum = "RETURN_PROCESSING"
  let EXPRESSCANCELLEDBYPARTNEREnum = "EXPRESS_CANCELLED_BY_PARTNER"
  let DELIVERYTOCUSTOMERRETURNEnum = "DELIVERY_TO_CUSTOMER_RETURN"
  let CROSSBORDERDELIVERYEnum = "CROSSBORDER_DELIVERY"
  let INTAKESORTINGBULKYCARGOEnum = "INTAKE_SORTING_BULKY_CARGO"
  let INTAKESORTINGSMALLGOODSEnum = "INTAKE_SORTING_SMALL_GOODS"
  let INTAKESORTINGDAILYEnum = "INTAKE_SORTING_DAILY"
  let FFSTORAGEBILLINGEnum = "FF_STORAGE_BILLING"
  let CANCELLEDORDERFEEQIEnum = "CANCELLED_ORDER_FEE_QI"
  let LATEORDEREXECUTIONFEEQIEnum = "LATE_ORDER_EXECUTION_FEE_QI"
  type TariffType = string

  //#endregion
