/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.FeedContentErrorDTO;
import org.openapitools.client.model.FeedStatusType;



/**
  * Информация о проверке содержимого прайс-листа, загруженного на Маркет.
 **/

public class FeedContentDTO  {
  
 /**
   * Количество предложений, в которых найдены ошибки на этапе загрузки прайс-листа. Выводится, если параметр `content status=OK`. 
  **/
  private Long rejectedOffersCount;

  private FeedStatusType status;

 /**
   * Количество предложений в прайс-листе. Выводится, если параметр `content status=OK`. 
  **/
  private Long totalOffersCount;

  private FeedContentErrorDTO error;

 /**
   * Количество предложений, в которых найдены ошибки на этапе загрузки прайс-листа. Выводится, если параметр &#x60;content status&#x3D;OK&#x60;. 
   * @return rejectedOffersCount
  **/
  public Long getRejectedOffersCount() {
    return rejectedOffersCount;
  }

  /**
    * Set rejectedOffersCount
  **/
  public void setRejectedOffersCount(Long rejectedOffersCount) {
    this.rejectedOffersCount = rejectedOffersCount;
  }

  public FeedContentDTO rejectedOffersCount(Long rejectedOffersCount) {
    this.rejectedOffersCount = rejectedOffersCount;
    return this;
  }

 /**
   * Get status
   * @return status
  **/
  public FeedStatusType getStatus() {
    return status;
  }

  /**
    * Set status
  **/
  public void setStatus(FeedStatusType status) {
    this.status = status;
  }

  public FeedContentDTO status(FeedStatusType status) {
    this.status = status;
    return this;
  }

 /**
   * Количество предложений в прайс-листе. Выводится, если параметр &#x60;content status&#x3D;OK&#x60;. 
   * @return totalOffersCount
  **/
  public Long getTotalOffersCount() {
    return totalOffersCount;
  }

  /**
    * Set totalOffersCount
  **/
  public void setTotalOffersCount(Long totalOffersCount) {
    this.totalOffersCount = totalOffersCount;
  }

  public FeedContentDTO totalOffersCount(Long totalOffersCount) {
    this.totalOffersCount = totalOffersCount;
    return this;
  }

 /**
   * Get error
   * @return error
  **/
  public FeedContentErrorDTO getError() {
    return error;
  }

  /**
    * Set error
  **/
  public void setError(FeedContentErrorDTO error) {
    this.error = error;
  }

  public FeedContentDTO error(FeedContentErrorDTO error) {
    this.error = error;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedContentDTO {\n");
    
    sb.append("    rejectedOffersCount: ").append(toIndentedString(rejectedOffersCount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalOffersCount: ").append(toIndentedString(totalOffersCount)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

