/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.SkuBidRecommendationItemDTO;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Список товаров с рекомендованными ставками.
 **/
@ApiModel(description = "Список товаров с рекомендованными ставками.")
public class GetBidsRecommendationsResponseDTO {
  
  @SerializedName("recommendations")
  private List<SkuBidRecommendationItemDTO> recommendations = null;

  /**
   * Список товаров с рекомендованными ставками.
   **/
  @ApiModelProperty(required = true, value = "Список товаров с рекомендованными ставками.")
  public List<SkuBidRecommendationItemDTO> getRecommendations() {
    return recommendations;
  }
  public void setRecommendations(List<SkuBidRecommendationItemDTO> recommendations) {
    this.recommendations = recommendations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBidsRecommendationsResponseDTO getBidsRecommendationsResponseDTO = (GetBidsRecommendationsResponseDTO) o;
    return (this.recommendations == null ? getBidsRecommendationsResponseDTO.recommendations == null : this.recommendations.equals(getBidsRecommendationsResponseDTO.recommendations));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.recommendations == null ? 0: this.recommendations.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBidsRecommendationsResponseDTO {\n");
    
    sb.append("  recommendations: ").append(recommendations).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
