/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.OfferPriceDTO;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Запрос на установку цен на товары.
 **/
@ApiModel(description = "Запрос на установку цен на товары.")
public class UpdatePricesRequest {
  
  @SerializedName("offers")
  private List<OfferPriceDTO> offers = null;

  /**
   * Список товаров.
   **/
  @ApiModelProperty(required = true, value = "Список товаров.")
  public List<OfferPriceDTO> getOffers() {
    return offers;
  }
  public void setOffers(List<OfferPriceDTO> offers) {
    this.offers = offers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePricesRequest updatePricesRequest = (UpdatePricesRequest) o;
    return (this.offers == null ? updatePricesRequest.offers == null : this.offers.equals(updatePricesRequest.offers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.offers == null ? 0: this.offers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePricesRequest {\n");
    
    sb.append("  offers: ").append(offers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
