(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Api_not_found_error_response.t : Запрашиваемый ресурс не найден.
 *)

type t = {
    status: Enums.apiresponsestatustype option [@default None];
    (* Список ошибок. *)
    errors: Api_error_dto.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Запрашиваемый ресурс не найден. *)
let create () : t = {
    status = None;
    errors = [];
}

