(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Generate_united_netting_report_request.t : Данные, необходимые для генерации отчета: идентификатор магазина, период, за который нужен отчет, а также фильтры. 
 *)

type t = {
    (* Идентификатор бизнеса. *)
    business_id: int64;
    (* {% note warning \''\'' %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Начало периода, включительно.  *)
    date_time_from: string option [@default None];
    (* {% note warning \''\'' %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Конец периода, включительно. Максимальный период — 1 год.  *)
    date_time_to: string option [@default None];
    (* Начало периода, включительно. *)
    date_from: string option [@default None];
    (* Конец периода, включительно. Максимальный период — 1 год. *)
    date_to: string option [@default None];
    (* Номер платежного поручения. *)
    bank_order_id: int64 option [@default None];
    (* Дата платежного поручения. *)
    bank_order_date_time: string option [@default None];
    (* Список моделей, которые нужны в отчете.  *)
    placement_programs: Enums.placementtype list;
    (* Список ИНН, которые нужны в отчете. *)
    inns: string list;
    (* Список магазинов, которые нужны в отчете. *)
    campaign_ids: int64 list;
} [@@deriving yojson { strict = false }, show ];;

(** Данные, необходимые для генерации отчета: идентификатор магазина, период, за который нужен отчет, а также фильтры.  *)
let create (business_id : int64) : t = {
    business_id = business_id;
    date_time_from = None;
    date_time_to = None;
    date_from = None;
    date_to = None;
    bank_order_id = None;
    bank_order_date_time = None;
    placement_programs = [];
    inns = [];
    campaign_ids = [];
}

