/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GoodsFeedbackCommentAuthorType : Тип автора:  * `USER` — пользователь. * `BUSINESS` — кабинет. 
/// Тип автора:  * `USER` — пользователь. * `BUSINESS` — кабинет. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GoodsFeedbackCommentAuthorType {
    #[serde(rename = "USER")]
    User,
    #[serde(rename = "BUSINESS")]
    Business,

}

impl std::fmt::Display for GoodsFeedbackCommentAuthorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::User => write!(f, "USER"),
            Self::Business => write!(f, "BUSINESS"),
        }
    }
}

impl Default for GoodsFeedbackCommentAuthorType {
    fn default() -> GoodsFeedbackCommentAuthorType {
        Self::User
    }
}

