# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GetQuarantineOffersRequest
Фильтрации товаров  В запросе можно указать либо фильтр offerIds, либо любые другие фильтры товаров. Совместное использование фильтра offerIds с другими фильтрациями приведет к ошибке. 

    GetQuarantineOffersRequest(;
        offerIds=nothing,
        cardStatuses=nothing,
        categoryIds=nothing,
        vendorNames=nothing,
        tags=nothing,
    )

    - offerIds::Vector{String} : Идентификаторы товаров, информация о которых нужна. &lt;br&gt;&lt;br&gt; ⚠️ Не используйте это поле одновременно с фильтрами по статусам карточек, категориям, брендам или тегам. Если вы хотите воспользоваться фильтрами, оставьте поле пустым. 
    - cardStatuses::Vector{OfferCardStatusType} : Фильтр по статусам карточек.  [Что такое карточка товара](https://yandex.ru/support/marketplace/assortment/content/index.html) 
    - categoryIds::Vector{Int64} : Фильтр по категориям на Маркете.
    - vendorNames::Vector{String} : Фильтр по брендам.
    - tags::Vector{String} : Фильтр по тегам.
"""
Base.@kwdef mutable struct GetQuarantineOffersRequest <: OpenAPI.APIModel
    offerIds::Union{Nothing, Vector{String}} = nothing
    cardStatuses::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OfferCardStatusType} }
    categoryIds::Union{Nothing, Vector{Int64}} = nothing
    vendorNames::Union{Nothing, Vector{String}} = nothing
    tags::Union{Nothing, Vector{String}} = nothing

    function GetQuarantineOffersRequest(offerIds, cardStatuses, categoryIds, vendorNames, tags, )
        OpenAPI.validate_property(GetQuarantineOffersRequest, Symbol("offerIds"), offerIds)
        OpenAPI.validate_property(GetQuarantineOffersRequest, Symbol("cardStatuses"), cardStatuses)
        OpenAPI.validate_property(GetQuarantineOffersRequest, Symbol("categoryIds"), categoryIds)
        OpenAPI.validate_property(GetQuarantineOffersRequest, Symbol("vendorNames"), vendorNames)
        OpenAPI.validate_property(GetQuarantineOffersRequest, Symbol("tags"), tags)
        return new(offerIds, cardStatuses, categoryIds, vendorNames, tags, )
    end
end # type GetQuarantineOffersRequest

const _property_types_GetQuarantineOffersRequest = Dict{Symbol,String}(Symbol("offerIds")=>"Vector{String}", Symbol("cardStatuses")=>"Vector{OfferCardStatusType}", Symbol("categoryIds")=>"Vector{Int64}", Symbol("vendorNames")=>"Vector{String}", Symbol("tags")=>"Vector{String}", )
OpenAPI.property_type(::Type{ GetQuarantineOffersRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetQuarantineOffersRequest[name]))}

function check_required(o::GetQuarantineOffersRequest)
    true
end

function OpenAPI.validate_property(::Type{ GetQuarantineOffersRequest }, name::Symbol, val)
    if name === Symbol("offerIds")
        OpenAPI.validate_param(name, "GetQuarantineOffersRequest", :maxItems, val, 500)
        OpenAPI.validate_param(name, "GetQuarantineOffersRequest", :minItems, val, 1)
    end
    if name === Symbol("cardStatuses")
        OpenAPI.validate_param(name, "GetQuarantineOffersRequest", :minItems, val, 1)
    end
    if name === Symbol("categoryIds")
        OpenAPI.validate_param(name, "GetQuarantineOffersRequest", :minItems, val, 1)
    end
    if name === Symbol("vendorNames")
        OpenAPI.validate_param(name, "GetQuarantineOffersRequest", :minItems, val, 1)
    end
    if name === Symbol("tags")
        OpenAPI.validate_param(name, "GetQuarantineOffersRequest", :minItems, val, 1)
    end
end
