// tslint:disable
/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Изменился ли статус заказа:  * `OK` — статус изменен.  * `ERROR` — статус не изменен. В этом случае появится сообщение об ошибке в параметре `errorDetails`. 
 * @export
 * @enum {string}
 */
export enum OrderUpdateStatusType {
    Ok = 'OK',
    Error = 'ERROR'
}

export function OrderUpdateStatusTypeFromJSON(json: any): OrderUpdateStatusType {
    return json as OrderUpdateStatusType;
}

export function OrderUpdateStatusTypeToJSON(value?: OrderUpdateStatusType): any {
    return value as any;
}

