/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateOfferMappingEntryDto : Список товаров.  В теле запроса можно передать от одного до 500 товаров.  Обязательный параметр. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOfferMappingEntryDto {
    #[serde(rename = "mapping", skip_serializing_if = "Option::is_none")]
    pub mapping: Option<Box<models::OfferMappingDto>>,
    #[serde(rename = "awaitingModerationMapping", skip_serializing_if = "Option::is_none")]
    pub awaiting_moderation_mapping: Option<Box<models::OfferMappingDto>>,
    #[serde(rename = "rejectedMapping", skip_serializing_if = "Option::is_none")]
    pub rejected_mapping: Option<Box<models::OfferMappingDto>>,
    #[serde(rename = "offer", skip_serializing_if = "Option::is_none")]
    pub offer: Option<Box<models::UpdateMappingsOfferDto>>,
}

impl UpdateOfferMappingEntryDto {
    /// Список товаров.  В теле запроса можно передать от одного до 500 товаров.  Обязательный параметр. 
    pub fn new() -> UpdateOfferMappingEntryDto {
        UpdateOfferMappingEntryDto {
            mapping: None,
            awaiting_moderation_mapping: None,
            rejected_mapping: None,
            offer: None,
        }
    }
}

