/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ympa_aspnetcore_server.Converters;

namespace ympa_aspnetcore_server.Models
{ 
        /// <summary>
        /// Предупреждение, которое появилось при добавлении товара:  * `DEEP_DISCOUNT_OFFER` — большая разница с ценой в каталоге. Проверьте, нет ли ошибки.  * `CATALOG_PRICE_IS_LOWER_THAN_PROMO` — [базовая цена](*basic-price) в кабинете ниже цены по акции. У товара в акции будет отображаться базовая цена.  * `SHOP_PRICES_ARE_LOWER_THAN_PROMO` — цена в отдельном магазине ниже цены по акции. У товара в акции будет отображаться цена в магазине. Для остальных магазинов будет действовать цена по акции.  * `PROMOCODE_PRICE_MORE_THAN_MAX_FAIR_PRICE` — в отдельном магазине цена с учетом промокода выше максимально возможной цены. Товар не будет участвовать в акции.  * `SHOP_OFFER_NOT_ELIGIBLE_FOR_PROMO` — товар в отдельном магазине не подходит под условия акции. 
        /// </summary>
        /// <value>Предупреждение, которое появилось при добавлении товара:  * `DEEP_DISCOUNT_OFFER` — большая разница с ценой в каталоге. Проверьте, нет ли ошибки.  * `CATALOG_PRICE_IS_LOWER_THAN_PROMO` — [базовая цена](*basic-price) в кабинете ниже цены по акции. У товара в акции будет отображаться базовая цена.  * `SHOP_PRICES_ARE_LOWER_THAN_PROMO` — цена в отдельном магазине ниже цены по акции. У товара в акции будет отображаться цена в магазине. Для остальных магазинов будет действовать цена по акции.  * `PROMOCODE_PRICE_MORE_THAN_MAX_FAIR_PRICE` — в отдельном магазине цена с учетом промокода выше максимально возможной цены. Товар не будет участвовать в акции.  * `SHOP_OFFER_NOT_ELIGIBLE_FOR_PROMO` — товар в отдельном магазине не подходит под условия акции. </value>
        [TypeConverter(typeof(CustomEnumConverter<PromoOfferUpdateWarningCodeType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PromoOfferUpdateWarningCodeType
        {
            
            /// <summary>
            /// Enum DEEPDISCOUNTOFFEREnum for DEEP_DISCOUNT_OFFER
            /// </summary>
            [EnumMember(Value = "DEEP_DISCOUNT_OFFER")]
            DEEPDISCOUNTOFFEREnum = 1,
            
            /// <summary>
            /// Enum CATALOGPRICEISLOWERTHANPROMOEnum for CATALOG_PRICE_IS_LOWER_THAN_PROMO
            /// </summary>
            [EnumMember(Value = "CATALOG_PRICE_IS_LOWER_THAN_PROMO")]
            CATALOGPRICEISLOWERTHANPROMOEnum = 2,
            
            /// <summary>
            /// Enum SHOPPRICESARELOWERTHANPROMOEnum for SHOP_PRICES_ARE_LOWER_THAN_PROMO
            /// </summary>
            [EnumMember(Value = "SHOP_PRICES_ARE_LOWER_THAN_PROMO")]
            SHOPPRICESARELOWERTHANPROMOEnum = 3,
            
            /// <summary>
            /// Enum PROMOCODEPRICEMORETHANMAXFAIRPRICEEnum for PROMOCODE_PRICE_MORE_THAN_MAX_FAIR_PRICE
            /// </summary>
            [EnumMember(Value = "PROMOCODE_PRICE_MORE_THAN_MAX_FAIR_PRICE")]
            PROMOCODEPRICEMORETHANMAXFAIRPRICEEnum = 4,
            
            /// <summary>
            /// Enum SHOPOFFERNOTELIGIBLEFORPROMOEnum for SHOP_OFFER_NOT_ELIGIBLE_FOR_PROMO
            /// </summary>
            [EnumMember(Value = "SHOP_OFFER_NOT_ELIGIBLE_FOR_PROMO")]
            SHOPOFFERNOTELIGIBLEFORPROMOEnum = 5
        }
}
