-module(ympa_erlang_client_mappings_offer_info_dto).

-export([encode/1]).

-export_type([ympa_erlang_client_mappings_offer_info_dto/0]).

-type ympa_erlang_client_mappings_offer_info_dto() ::
    #{ 'name' => binary(),
       'shopSku' => binary(),
       'category' => binary(),
       'vendor' => binary(),
       'vendorCode' => binary(),
       'description' => binary(),
       'id' => binary(),
       'feedId' => integer(),
       'barcodes' => list(),
       'urls' => list(),
       'pictures' => list(),
       'manufacturer' => binary(),
       'manufacturerCountries' => list(),
       'minShipment' => integer(),
       'transportUnitSize' => integer(),
       'quantumOfSupply' => integer(),
       'deliveryDurationDays' => integer(),
       'boxCount' => integer(),
       'customsCommodityCodes' => list(),
       'weightDimensions' => ympa_erlang_client_offer_weight_dimensions_dto:ympa_erlang_client_offer_weight_dimensions_dto(),
       'supplyScheduleDays' => list(),
       'shelfLifeDays' => integer(),
       'lifeTimeDays' => integer(),
       'guaranteePeriodDays' => integer(),
       'processingState' => ympa_erlang_client_offer_processing_state_dto:ympa_erlang_client_offer_processing_state_dto(),
       'availability' => ympa_erlang_client_offer_availability_status_type:ympa_erlang_client_offer_availability_status_type(),
       'shelfLife' => ympa_erlang_client_time_period_dto:ympa_erlang_client_time_period_dto(),
       'lifeTime' => ympa_erlang_client_time_period_dto:ympa_erlang_client_time_period_dto(),
       'guaranteePeriod' => ympa_erlang_client_time_period_dto:ympa_erlang_client_time_period_dto(),
       'certificate' => binary()
     }.

encode(#{ 'name' := Name,
          'shopSku' := ShopSku,
          'category' := Category,
          'vendor' := Vendor,
          'vendorCode' := VendorCode,
          'description' := Description,
          'id' := Id,
          'feedId' := FeedId,
          'barcodes' := Barcodes,
          'urls' := Urls,
          'pictures' := Pictures,
          'manufacturer' := Manufacturer,
          'manufacturerCountries' := ManufacturerCountries,
          'minShipment' := MinShipment,
          'transportUnitSize' := TransportUnitSize,
          'quantumOfSupply' := QuantumOfSupply,
          'deliveryDurationDays' := DeliveryDurationDays,
          'boxCount' := BoxCount,
          'customsCommodityCodes' := CustomsCommodityCodes,
          'weightDimensions' := WeightDimensions,
          'supplyScheduleDays' := SupplyScheduleDays,
          'shelfLifeDays' := ShelfLifeDays,
          'lifeTimeDays' := LifeTimeDays,
          'guaranteePeriodDays' := GuaranteePeriodDays,
          'processingState' := ProcessingState,
          'availability' := Availability,
          'shelfLife' := ShelfLife,
          'lifeTime' := LifeTime,
          'guaranteePeriod' := GuaranteePeriod,
          'certificate' := Certificate
        }) ->
    #{ 'name' => Name,
       'shopSku' => ShopSku,
       'category' => Category,
       'vendor' => Vendor,
       'vendorCode' => VendorCode,
       'description' => Description,
       'id' => Id,
       'feedId' => FeedId,
       'barcodes' => Barcodes,
       'urls' => Urls,
       'pictures' => Pictures,
       'manufacturer' => Manufacturer,
       'manufacturerCountries' => ManufacturerCountries,
       'minShipment' => MinShipment,
       'transportUnitSize' => TransportUnitSize,
       'quantumOfSupply' => QuantumOfSupply,
       'deliveryDurationDays' => DeliveryDurationDays,
       'boxCount' => BoxCount,
       'customsCommodityCodes' => CustomsCommodityCodes,
       'weightDimensions' => WeightDimensions,
       'supplyScheduleDays' => SupplyScheduleDays,
       'shelfLifeDays' => ShelfLifeDays,
       'lifeTimeDays' => LifeTimeDays,
       'guaranteePeriodDays' => GuaranteePeriodDays,
       'processingState' => ProcessingState,
       'availability' => Availability,
       'shelfLife' => ShelfLife,
       'lifeTime' => LifeTime,
       'guaranteePeriod' => GuaranteePeriod,
       'certificate' => Certificate
     }.
