-module(ympa_erlang_client_order_dto).

-export([encode/1]).

-export_type([ympa_erlang_client_order_dto/0]).

-type ympa_erlang_client_order_dto() ::
    #{ 'id' => integer(),
       'status' => ympa_erlang_client_order_status_type:ympa_erlang_client_order_status_type(),
       'substatus' => ympa_erlang_client_order_substatus_type:ympa_erlang_client_order_substatus_type(),
       'creationDate' => binary(),
       'updatedAt' => binary(),
       'currency' => ympa_erlang_client_currency_type:ympa_erlang_client_currency_type(),
       'itemsTotal' => integer(),
       'deliveryTotal' => integer(),
       'buyerItemsTotal' => integer(),
       'buyerTotal' => integer(),
       'buyerItemsTotalBeforeDiscount' => integer(),
       'buyerTotalBeforeDiscount' => integer(),
       'paymentType' => ympa_erlang_client_order_payment_type:ympa_erlang_client_order_payment_type(),
       'paymentMethod' => ympa_erlang_client_order_payment_method_type:ympa_erlang_client_order_payment_method_type(),
       'fake' => boolean(),
       'items' := list(),
       'subsidies' => list(),
       'delivery' => ympa_erlang_client_order_delivery_dto:ympa_erlang_client_order_delivery_dto(),
       'buyer' => ympa_erlang_client_order_buyer_dto:ympa_erlang_client_order_buyer_dto(),
       'notes' => binary(),
       'taxSystem' => ympa_erlang_client_order_tax_system_type:ympa_erlang_client_order_tax_system_type(),
       'cancelRequested' => boolean(),
       'expiryDate' => binary()
     }.

encode(#{ 'id' := Id,
          'status' := Status,
          'substatus' := Substatus,
          'creationDate' := CreationDate,
          'updatedAt' := UpdatedAt,
          'currency' := Currency,
          'itemsTotal' := ItemsTotal,
          'deliveryTotal' := DeliveryTotal,
          'buyerItemsTotal' := BuyerItemsTotal,
          'buyerTotal' := BuyerTotal,
          'buyerItemsTotalBeforeDiscount' := BuyerItemsTotalBeforeDiscount,
          'buyerTotalBeforeDiscount' := BuyerTotalBeforeDiscount,
          'paymentType' := PaymentType,
          'paymentMethod' := PaymentMethod,
          'fake' := Fake,
          'items' := Items,
          'subsidies' := Subsidies,
          'delivery' := Delivery,
          'buyer' := Buyer,
          'notes' := Notes,
          'taxSystem' := TaxSystem,
          'cancelRequested' := CancelRequested,
          'expiryDate' := ExpiryDate
        }) ->
    #{ 'id' => Id,
       'status' => Status,
       'substatus' => Substatus,
       'creationDate' => CreationDate,
       'updatedAt' => UpdatedAt,
       'currency' => Currency,
       'itemsTotal' => ItemsTotal,
       'deliveryTotal' => DeliveryTotal,
       'buyerItemsTotal' => BuyerItemsTotal,
       'buyerTotal' => BuyerTotal,
       'buyerItemsTotalBeforeDiscount' => BuyerItemsTotalBeforeDiscount,
       'buyerTotalBeforeDiscount' => BuyerTotalBeforeDiscount,
       'paymentType' => PaymentType,
       'paymentMethod' => PaymentMethod,
       'fake' => Fake,
       'items' => Items,
       'subsidies' => Subsidies,
       'delivery' => Delivery,
       'buyer' => Buyer,
       'notes' => Notes,
       'taxSystem' => TaxSystem,
       'cancelRequested' => CancelRequested,
       'expiryDate' => ExpiryDate
     }.
