-module(ympa_erlang_client_base_offer_dto).

-export([encode/1]).

-export_type([ympa_erlang_client_base_offer_dto/0]).

-type ympa_erlang_client_base_offer_dto() ::
    #{ 'offerId' := binary(),
       'name' => binary(),
       'marketCategoryId' => integer(),
       'category' => binary(),
       'pictures' => list(),
       'videos' => list(),
       'manuals' => list(),
       'vendor' => binary(),
       'barcodes' => list(),
       'description' => binary(),
       'manufacturerCountries' => list(),
       'weightDimensions' => ympa_erlang_client_offer_weight_dimensions_dto:ympa_erlang_client_offer_weight_dimensions_dto(),
       'vendorCode' => binary(),
       'tags' => list(),
       'shelfLife' => ympa_erlang_client_time_period_dto:ympa_erlang_client_time_period_dto(),
       'lifeTime' => ympa_erlang_client_time_period_dto:ympa_erlang_client_time_period_dto(),
       'guaranteePeriod' => ympa_erlang_client_time_period_dto:ympa_erlang_client_time_period_dto(),
       'customsCommodityCode' => binary(),
       'certificates' => list(),
       'boxCount' => integer(),
       'condition' => ympa_erlang_client_offer_condition_dto:ympa_erlang_client_offer_condition_dto(),
       'type' => ympa_erlang_client_offer_type:ympa_erlang_client_offer_type(),
       'downloadable' => boolean(),
       'adult' => boolean(),
       'age' => ympa_erlang_client_age_dto:ympa_erlang_client_age_dto(),
       'params' => list()
     }.

encode(#{ 'offerId' := OfferId,
          'name' := Name,
          'marketCategoryId' := MarketCategoryId,
          'category' := Category,
          'pictures' := Pictures,
          'videos' := Videos,
          'manuals' := Manuals,
          'vendor' := Vendor,
          'barcodes' := Barcodes,
          'description' := Description,
          'manufacturerCountries' := ManufacturerCountries,
          'weightDimensions' := WeightDimensions,
          'vendorCode' := VendorCode,
          'tags' := Tags,
          'shelfLife' := ShelfLife,
          'lifeTime' := LifeTime,
          'guaranteePeriod' := GuaranteePeriod,
          'customsCommodityCode' := CustomsCommodityCode,
          'certificates' := Certificates,
          'boxCount' := BoxCount,
          'condition' := Condition,
          'type' := Type,
          'downloadable' := Downloadable,
          'adult' := Adult,
          'age' := Age,
          'params' := Params
        }) ->
    #{ 'offerId' => OfferId,
       'name' => Name,
       'marketCategoryId' => MarketCategoryId,
       'category' => Category,
       'pictures' => Pictures,
       'videos' => Videos,
       'manuals' => Manuals,
       'vendor' => Vendor,
       'barcodes' => Barcodes,
       'description' => Description,
       'manufacturerCountries' => ManufacturerCountries,
       'weightDimensions' => WeightDimensions,
       'vendorCode' => VendorCode,
       'tags' => Tags,
       'shelfLife' => ShelfLife,
       'lifeTime' => LifeTime,
       'guaranteePeriod' => GuaranteePeriod,
       'customsCommodityCode' => CustomsCommodityCode,
       'certificates' => Certificates,
       'boxCount' => BoxCount,
       'condition' => Condition,
       'type' => Type,
       'downloadable' => Downloadable,
       'adult' => Adult,
       'age' => Age,
       'params' => Params
     }.
