# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ПартнерскийAPIМаркета.Model.GenerateShelfsStatisticsRequest do
  @moduledoc """
  Данные, необходимые для генерации отчета. 
  """

  @derive Jason.Encoder
  defstruct [
    :businessId,
    :dateFrom,
    :dateTo,
    :attributionType
  ]

  @type t :: %__MODULE__{
    :businessId => integer(),
    :dateFrom => Date.t,
    :dateTo => Date.t,
    :attributionType => ПартнерскийAPIМаркета.Model.ShelfsStatisticsAttributionType.t
  }

  alias ПартнерскийAPIМаркета.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:dateFrom, :date, nil)
     |> Deserializer.deserialize(:dateTo, :date, nil)
     |> Deserializer.deserialize(:attributionType, :struct, ПартнерскийAPIМаркета.Model.ShelfsStatisticsAttributionType)
  end
end

