export * from './bids.service';
import { BidsService } from './bids.service';
export * from './businessOfferMappings.service';
import { BusinessOfferMappingsService } from './businessOfferMappings.service';
export * from './businesses.service';
import { BusinessesService } from './businesses.service';
export * from './campaigns.service';
import { CampaignsService } from './campaigns.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './chats.service';
import { ChatsService } from './chats.service';
export * from './content.service';
import { ContentService } from './content.service';
export * from './dbs.service';
import { DbsService } from './dbs.service';
export * from './deliveryServices.service';
import { DeliveryServicesService } from './deliveryServices.service';
export * from './express.service';
import { ExpressService } from './express.service';
export * from './fbs.service';
import { FbsService } from './fbs.service';
export * from './fby.service';
import { FbyService } from './fby.service';
export * from './feedbacks.service';
import { FeedbacksService } from './feedbacks.service';
export * from './feeds.service';
import { FeedsService } from './feeds.service';
export * from './goodsFeedback.service';
import { GoodsFeedbackService } from './goodsFeedback.service';
export * from './goodsStats.service';
import { GoodsStatsService } from './goodsStats.service';
export * from './hiddenOffers.service';
import { HiddenOffersService } from './hiddenOffers.service';
export * from './models.service';
import { ModelsService } from './models.service';
export * from './offerMappings.service';
import { OfferMappingsService } from './offerMappings.service';
export * from './offers.service';
import { OffersService } from './offers.service';
export * from './orderBusinessInformation.service';
import { OrderBusinessInformationService } from './orderBusinessInformation.service';
export * from './orderDelivery.service';
import { OrderDeliveryService } from './orderDelivery.service';
export * from './orderLabels.service';
import { OrderLabelsService } from './orderLabels.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './ordersStats.service';
import { OrdersStatsService } from './ordersStats.service';
export * from './outletLicenses.service';
import { OutletLicensesService } from './outletLicenses.service';
export * from './outlets.service';
import { OutletsService } from './outlets.service';
export * from './priceQuarantine.service';
import { PriceQuarantineService } from './priceQuarantine.service';
export * from './prices.service';
import { PricesService } from './prices.service';
export * from './promos.service';
import { PromosService } from './promos.service';
export * from './ratings.service';
import { RatingsService } from './ratings.service';
export * from './regions.service';
import { RegionsService } from './regions.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './returns.service';
import { ReturnsService } from './returns.service';
export * from './shipments.service';
import { ShipmentsService } from './shipments.service';
export * from './stocks.service';
import { StocksService } from './stocks.service';
export * from './tariffs.service';
import { TariffsService } from './tariffs.service';
export * from './warehouses.service';
import { WarehousesService } from './warehouses.service';
export const APIS = [BidsService, BusinessOfferMappingsService, BusinessesService, CampaignsService, CategoriesService, ChatsService, ContentService, DbsService, DeliveryServicesService, ExpressService, FbsService, FbyService, FeedbacksService, FeedsService, GoodsFeedbackService, GoodsStatsService, HiddenOffersService, ModelsService, OfferMappingsService, OffersService, OrderBusinessInformationService, OrderDeliveryService, OrderLabelsService, OrdersService, OrdersStatsService, OutletLicensesService, OutletsService, PriceQuarantineService, PricesService, PromosService, RatingsService, RegionsService, ReportsService, ReturnsService, ShipmentsService, StocksService, TariffsService, WarehousesService];
