/* tslint:disable */
/* eslint-disable */
/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OfferMappingSuggestionsListDTO } from './OfferMappingSuggestionsListDTO';
import {
    OfferMappingSuggestionsListDTOFromJSON,
    OfferMappingSuggestionsListDTOFromJSONTyped,
    OfferMappingSuggestionsListDTOToJSON,
} from './OfferMappingSuggestionsListDTO';
import type { ApiResponseStatusType } from './ApiResponseStatusType';
import {
    ApiResponseStatusTypeFromJSON,
    ApiResponseStatusTypeFromJSONTyped,
    ApiResponseStatusTypeToJSON,
} from './ApiResponseStatusType';

/**
 * Ответ со списком рекомендованных карточек товара.
 * @export
 * @interface GetSuggestedOfferMappingEntriesResponse
 */
export interface GetSuggestedOfferMappingEntriesResponse {
    /**
     * 
     * @type {ApiResponseStatusType}
     * @memberof GetSuggestedOfferMappingEntriesResponse
     */
    status?: ApiResponseStatusType;
    /**
     * 
     * @type {OfferMappingSuggestionsListDTO}
     * @memberof GetSuggestedOfferMappingEntriesResponse
     */
    result?: OfferMappingSuggestionsListDTO;
}



/**
 * Check if a given object implements the GetSuggestedOfferMappingEntriesResponse interface.
 */
export function instanceOfGetSuggestedOfferMappingEntriesResponse(value: object): value is GetSuggestedOfferMappingEntriesResponse {
    return true;
}

export function GetSuggestedOfferMappingEntriesResponseFromJSON(json: any): GetSuggestedOfferMappingEntriesResponse {
    return GetSuggestedOfferMappingEntriesResponseFromJSONTyped(json, false);
}

export function GetSuggestedOfferMappingEntriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSuggestedOfferMappingEntriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : ApiResponseStatusTypeFromJSON(json['status']),
        'result': json['result'] == null ? undefined : OfferMappingSuggestionsListDTOFromJSON(json['result']),
    };
}

export function GetSuggestedOfferMappingEntriesResponseToJSON(value?: GetSuggestedOfferMappingEntriesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': ApiResponseStatusTypeToJSON(value['status']),
        'result': OfferMappingSuggestionsListDTOToJSON(value['result']),
    };
}

