/* tslint:disable */
/* eslint-disable */
/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoodsFeedbackCommentAuthorType } from './GoodsFeedbackCommentAuthorType';
import {
    GoodsFeedbackCommentAuthorTypeFromJSON,
    GoodsFeedbackCommentAuthorTypeFromJSONTyped,
    GoodsFeedbackCommentAuthorTypeToJSON,
} from './GoodsFeedbackCommentAuthorType';

/**
 * Информация об авторе комментария.
 * @export
 * @interface GoodsFeedbackCommentAuthorDTO
 */
export interface GoodsFeedbackCommentAuthorDTO {
    /**
     * 
     * @type {GoodsFeedbackCommentAuthorType}
     * @memberof GoodsFeedbackCommentAuthorDTO
     */
    type?: GoodsFeedbackCommentAuthorType;
    /**
     * Имя автора или название кабинета.
     * @type {string}
     * @memberof GoodsFeedbackCommentAuthorDTO
     */
    name?: string;
}



/**
 * Check if a given object implements the GoodsFeedbackCommentAuthorDTO interface.
 */
export function instanceOfGoodsFeedbackCommentAuthorDTO(value: object): value is GoodsFeedbackCommentAuthorDTO {
    return true;
}

export function GoodsFeedbackCommentAuthorDTOFromJSON(json: any): GoodsFeedbackCommentAuthorDTO {
    return GoodsFeedbackCommentAuthorDTOFromJSONTyped(json, false);
}

export function GoodsFeedbackCommentAuthorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoodsFeedbackCommentAuthorDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : GoodsFeedbackCommentAuthorTypeFromJSON(json['type']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GoodsFeedbackCommentAuthorDTOToJSON(value?: GoodsFeedbackCommentAuthorDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': GoodsFeedbackCommentAuthorTypeToJSON(value['type']),
        'name': value['name'],
    };
}

